export const translationKeys = {
  Users: "用户",
  StaffStatuses: "员工状态",
  Genders: "性别",
  Roles: "角色",
  Category: "类别",
  Product: "产品",
  Modules: "模块",
  Actions: "操作",
  Permissions: "权限",
  CompanyConfiguration: "公司配置",
  SystemConfiguration: "系统配置",
  DistributionReport: "分发报告",
  AccessControl: "访问控制",
  Products: "产品",
  Settings: "设置",
  Reports: "报告",
  ProfilePicture: "头像",
  FullName: "全名",
  Email: "电子邮件",
  Password: "密码",
  PhoneNumber: "电话号码",
  DateOfBirth: "出生日期",
  RecruitmentDate: "招聘日期",
  UserRole: "用户角色",
  Status: "状态",
  Gender: "性别",
  Description: "描述",
  RoleName: "角色名称",
  CategoryName: "类别名称",
  ProductName: "产品名称",
  Price: "价格",
  Images: "图片",
  NumberOfReviews: "评论数量",
  SalesVolume: "销售量",
  StockStatus: "库存状态",
  DiscountPercentage: "折扣百分比",
  TimeAdded: "添加时间",
  Brand: "品牌",
  MaterialsUsed: "使用材料",
  Color: "颜色",
  Size: "尺寸",
  Features: "特征",
  Tags: "标签",
  WarrantyPeriod: "保修期",
  ManufacturerDetails: "制造商详细信息",
  ModuleName: "模块名称",
  Action: "操作",
  Create: "创建",
  Read: "读取",
  Update: "更新",
  Delete: "删除",
  CompanyLogo: "公司标志",
  CompanyName: "公司名称",
  CompanyGoogleMapLink: "公司 Google 地图链接",
  CompanyEmails: "公司电子邮件",
  CompanyPhoneNumbers: "公司电话号码",
  CompanySocialMediaLinks: "公司社交媒体链接",
  CompanyAddress: "公司地址",
  Location: "位置",
  Motto: "座右铭",
  SystemLogo: "系统标志",
  ApplicationName: "应用名称",
  ApplicationVersion: "应用版本",
  Language: "语言",
  GoogleConfiguration: "Google 配置",
  ClientId: "客户端 ID",
  ClientSecret: "客户端密钥",
  UserEmail: "用户电子邮件",
  UserPassword: "用户密码",
  AccessToken: "访问令牌",
  RefreshToken: "刷新令牌",
  StripeConfiguration: "Stripe 配置",
  PublishableKey: "发布密钥",
  SecretKey: "密钥",
  PaypalConfiguration: "Paypal 配置",
  JwtConfiguration: "JWT 配置",
  DatabaseConfiguration: "数据库配置",
  DatabaseUrl: "数据库 URL",
  FirebaseConfiguration: "Firebase 配置",
  ApiKey: "API 密钥",
  AuthDomain: "认证域",
  ProjectId: "项目 ID",
  StorageBucket: "存储桶",
  MessagingSenderId: "消息发送 ID",
  AppId: "应用 ID",
  TwilioConfiguration: "Twilio 配置",
  AccountSid: "账户 SID",
  AuthToken: "认证令牌",
  TwilioNumber: "Twilio 号码",
  AmazonS3Configuration: "Amazon S3 配置",
  AccessKeyId: "访问密钥 ID",
  BucketName: "存储桶名称",
  OpenAiConfiguration: "OpenAI 配置",
  LoginPageLayout: "登录页面布局",
  ApplicationDescription: "应用描述",
  MaintenanceMessage: "维护信息",
  MaintenanceMode: "维护模式",
  Name: "名称",
  Link: "链接",
  Icon: "图标",

  Home: "首页",
  Statistics: "统计",
  ExportCSV: "导出 CSV",
  SelectAll: "全选",
  Ascending: "升序",
  Descending: "降序",
  Refresh: "刷新",
  Filter: "过滤",
  Apply: "应用",
  Cancel: "取消",
  Reset: "重置",
  BulkDelete: "批量删除",
  BulkUpdate: "批量更新",
  DownloadCSV: "下载 CSV",
  ConfirmBulkDelete: "确认批量删除",
  SelectAction: "选择操作",
  NoRecordsFound: "未找到记录",
  QuickStats: "快速统计",
  Close: "关闭",
  AreYouSure: "你确定吗？",
  DoYouWantToLogout: "你想要登出吗？",
  Warning: "警告",
  YesLogout: "是的，登出！",
  LoggedOut: "已登出！",
  ProfileSettings: "个人资料设置",
  Settings: "设置",
  Logout: "登出",
  Role: "角色",
  Previous: "上一步",
  Next: "下一步",
  Records: "记录",
  Apply: "应用",
  Submit: "提交",
  Processing: "处理中...",
  Add: "添加",
  SelectAnOption: "选择一个选项",
  Browse: "浏览",
  AddFiles: "添加文件",
  Upload: "上传",
  Ok: "确定",
  QuickActions: "快速操作",
  UpdatePassword: "更新密码",
  CurrentPassword: "当前密码",
  NewPassword: "新密码",
  ConfirmNewPassword: "确认新密码",
  DeleteWarning: "你将无法恢复此操作！",
  YesDelete: "是的，删除！",
  Deleted: "已删除！",
  DeleteSuccess: "您的记录已被删除。",
  Error: "发生错误！",
  Success: "成功！",
  DeleteError: "删除记录时发生错误。",
  BulkUpdateSuccess: "您的记录已更新。",
  BulkUpdateError: "更新记录时发生错误。",
  ConfirmBulkDelete: "确认批量删除",
  ConfirmBulkDeleteMessage: "你确定要删除这些记录吗？",
  Cancelled: "已取消",
  StillLoggedIn: "你仍然已登录。",
  Profile: "个人资料",
  NoFileChosen: "未选择文件",

  WelcomeToPansikaOnline: "欢迎来到 Pansika Online",
  OneStopMarketplace: "您的一站式市场",
  ExploreProductRange: "探索我们广泛的产品范围，以满足您的所有需求。",
  MarketplaceProducts: "市场产品",
  StartShopping: "开始购物",
  ExclusiveOffers: "独家优惠",
  BestDealsForYou: "专为您准备的最佳交易",
  DontMissOffers: "不要错过我们限时提供的独家优惠和折扣。",
  ViewOffers: "查看优惠",
  NewArrivals: "新品上市",
  DiscoverWhatsNew: "发现最新产品",
  CheckLatestArrivals: "查看我们为您量身定制的各类最新产品。",
  SeeNewProducts: "查看新产品",

  // 类别
  TopCategories: "热门类别",
  ShopByCategory: "按类别购物",
  Electronics: "电子产品",
  LatestGadgets: "最新的电子设备和小工具",
  Fashion: "时尚",
  TrendyClothing: "时尚服装和配饰",
  HomeLiving: "家居生活",
  HomeEssentials: "舒适家居的必需品",
  KitchenDining: "厨房与餐厅",
  QualityKitchenware: "为每位家庭厨师提供的优质厨房用品",

  // 精选产品
  FeaturedProducts: "精选产品",
  SmartphoneXYZ: "智能手机 XYZ",
  WirelessEarbuds: "无线耳机",
  FitnessTracker: "健身追踪器",
  GamingLaptop: "游戏笔记本电脑",

  // 特点
  WhyChoosePansikaOnline: "为什么选择 Pansika Online？",
  FastShipping: "快速发货",
  FastShippingDesc: "快速高效地将您的订单送到您家门口。",
  SecurePayments: "安全支付",
  SecurePaymentsDesc: "使用我们的安全支付方式和数据保护，让您安心购物。",
  QualityAssurance: "质量保证",
  QualityAssuranceDesc: "我们确保所有产品在交付前都符合最高质量标准。",

  // 客户评价
  TestimonialQuote:
    "在 Pansika Online 购物的体验非常棒！产品的多样性和质量让我印象深刻。",
  TestimonialAuthor: "约翰·多",
  TestimonialPosition: "常客",

  // 行动呼吁
  JoinOurCommunity: "加入我们的社区",
  SubscribeDescription: "订阅我们的新闻通讯，以获取最新产品、特价优惠等信息。",
  SubscribeNow: "立即订阅",
  AboutUs: "关于我们",
  Categories: "类别",
  // 关于我们
  AboutPansikaOnline: "关于 Pansika Online",
  CommittedToYourExperience: "致力于您的购物体验",
  PansikaOnlineTeam: "Pansika Online 团队",
  OurVision: "我们的愿景",
  OurCoreValues: "我们的核心价值",
  CustomerSatisfaction: "客户满意度",
  CustomerSatisfactionDesc: "我们优先考虑客户的需求，并追求卓越。",
  Sustainability: "可持续发展",
  SustainabilityDesc: "我们致力于在运营中实施可持续做法。",
  CommunityEngagement: "社区参与",
  CommunityEngagementDesc: "我们积极参与并回馈所服务的社区。",

  // 常见问题
  FrequentlyAskedQuestions: "常见问题",
  PaymentMethodsQuestion: "您接受哪些支付方式？",
  PaymentMethodsAnswer: "我们接受所有主要信用卡、PayPal 和银行转账。",
  TrackOrderQuestion: "我如何跟踪我的订单？",
  TrackOrderAnswer: "您可以在帐户的“我的订单”部分跟踪您的订单状态。",
  ReturnPolicyQuestion: "您的退货政策是什么？",
  ReturnPolicyAnswer:
    "我们对所有商品提供 30 天的退货政策。有关更多详细信息，请参阅我们的退货政策页面。",
  InternationalShippingQuestion: "您提供国际运输吗？",
  InternationalShippingAnswer:
    "是的，我们向全球各国发货。运费可能因目的地而异。",
};
