export const translationKeys = {
  Users: "Users",
  UserManagement:'User Management',
  StaffStatuses: "Staff Statuses",
  Genders: "Genders",
  Roles: "Roles",
  Category: "Category",
  Product: "Products",
  Modules: "Modules",
  Actions: "Actions",
  Permissions: "Permissions",
  CompanyConfiguration: "Company",
  SystemConfiguration: "System",
  DistributionReport: "Distribution Report",
  AccessControl: "Access Control",
  Products: "Products",
  Settings: "Settings",
  Reports: "Reports",
  ProfilePicture: "Profile Picture",
  FullName: "Full Name",
  Email: "Email",
  Password: "Password",
  ConfirmPassword: "Confirm Password",
  PhoneNumber: "Phone Number",
  DateOfBirth: "Date Of Birth",
  RecruitmentDate: "Recruitment Date",
  UserRole: "User Role",
  Status: "Status",
  Tags: "Tags",
  Description: "Description",
  RoleName: "Role Name",
  CategoryName: "Category Name",
  ProductName: "Product Name",
  Price: "Price",
  Images: "images",
  NumberOfReviews: "Number of Reviews",
  SalesVolume: "Sales Volume",
  StockStatus: "Stock Status",
  DiscountPercentage: "Discount Percentage",
  TimeAdded: "Time Added",
  Brand: "Brand",
  MaterialsUsed: "Materials Used",
  Color: "Color",
  Size: "Size",
  Features: "Features",
  WarrantyPeriod: "Warranty Period",
  ManufacturerDetails: "Manufacturer Details",
  ModuleName: "Module Name",
  Action: "Action",
  Create: "Create",
  Read: "Read",
  Update: "Update",
  Delete: "Delete",
  CompanyLogo: "Company Logo",
  CompanyName: "Company Name",
  CompanyGoogleMapLink: "Company Google Map Link",
  CompanyEmails: "Company Emails",
  CompanyPhoneNumbers: "Company Phone Numbers",
  CompanySocialMediaLinks: "Company Social Media Links",
  CompanyAddress: "Company Address",
  Location: "Location",
  Motto: "Motto",
  SystemLogo: "System Logo",
  ApplicationName: "Application Name",
  ApplicationVersion: "Application Version",
  Language: "Language",
  GoogleConfiguration: "Google Configuration",
  ClientId: "Client ID",
  ClientSecret: "Client Secret",
  UserEmail: "User Email",
  UserPassword: "User Password",
  AccessToken: "Access Token",
  RefreshToken: "Refresh Token",
  StripeConfiguration: "Stripe Configuration",
  PublishableKey: "Publishable Key",
  SecretKey: "Secret Key",
  PaypalConfiguration: "Paypal Configuration",
  JwtConfiguration: "JWT Configuration",
  DatabaseConfiguration: "Database Configuration",
  DatabaseUrl: "Database URL",
  FirebaseConfiguration: "Firebase Configuration",
  ApiKey: "API Key",
  AuthDomain: "Auth Domain",
  ProjectId: "Project ID",
  StorageBucket: "Storage Bucket",
  MessagingSenderId: "Messaging Sender ID",
  AppId: "App ID",
  TwilioConfiguration: "Twilio Configuration",
  AccountSid: "Account SID",
  AuthToken: "Auth Token",
  TwilioNumber: "Twilio Number",
  AmazonS3Configuration: "Amazon S3 Configuration",
  AccessKeyId: "Access Key ID",
  BucketName: "Bucket Name",
  OpenAiConfiguration: "OpenAI Configuration",
  Login: "Login",
  LoginPageLayout: "Login Page Layout",
  ApplicationDescription: "Application Description",
  MaintenanceMessage: "Maintenance Message",
  MaintenanceMode: "Maintenance Mode",
  Name: "Name",
  Link: "link",
  Icon: "Icon",
  Home: "Home",
  Statistics: "Statistics",
  ExportCSV: "Export CSV",
  SelectAll: "Select All",
  Ascending: "Ascending",
  Descending: "Descending",
  Refresh: "Refresh",
  Filter: "Filter",
  Apply: "Apply",
  Cancel: "Cancel",
  Reset: "Reset",
  BulkDelete: "Bulk Delete",
  BulkUpdate: "Bulk Update",
  DownloadCSV: "Download CSV",
  ConfirmBulkDelete: "Confirm Bulk Delete",
  SelectAction: "Select Action",
  NoRecordsFound: "No Records Found",
  QuickStats: "Quick Stats",
  Close: "Close",
  AreYouSure: "Are you sure?",
  DoYouWantToLogout: "Do you want to logout?",
  Warning: "Warning",
  YesLogout: "Yes, Log me out!",
  LoggedOut: "Logged out!",
  ProfileSettings: "Profile settings",
  Settings: "Settings",
  Logout: "Logout",
  Role: "Role",
  Previous: "Previous",
  Next: "Next",
  Records: "Records",
  Submit: "Submit",
  Processing: "Processing...",
  Add: "Add",
  SelectAnOption: "Select an option",
  Browse: "Browse",
  AddFiles: "Add Files",
  Upload: "Upload",
  Ok: "Ok",
  Dashboard: "Dashboard",
  QuickActions: "Quick Actions",
  UpdatePassword: "Update Password",
  CurrentPassword: "Current Password",
  NewPassword: "New Password",
  ConfirmNewPassword: "Confirm New Password",
  DeleteWarning: "You Won't Be Able To Revert This!",
  YesDelete: "Yes, Delete It!",
  Deleted: "Deleted!",
  DeleteSuccess: "Your Record has been deleted.",
  Error: "An error occurred!",
  Success: "Success!",
  DeleteError: "An error occurred while deleting your record.",
  BulkUpdateSuccess: "Your records have been updated.",
  BulkUpdateError: "An error occurred while updating your records.",
  ConfirmBulkDeleteMessage: "Are you sure you want to delete these records?",
  Cancelled: "Cancelled",
  StillLoggedIn: "You Are still logged in.",
  Profile: "Profile",
  NoFileChosen: "No file chosen",
  Materials: "Materials",
  Shops: "My Shops",
  Stores: "My Stores",
  ShopName: "Shop Name",
  Owner: "Owner",
  Address: "Address",
  ContactNumber: "Contact Number",
  Shop: "Shop",
  Orders: "Orders",
  Sales: "Sales",
  OrderNumber: "Order Number",
  Customer: "Customer",
  TotalAmount: "Total Amount",
  OrderDate: "Order Date",
  Reviews: "Reviews",
  Feedback: "Feedback",
  Rating: "Rating",
  Comment: "Comment",
  ReviewDate: "Review Date",
  ShopDetails: "Shop Details",
  PasswordRequired: "Password is required.",
  PasswordMinLength: "Password must be at least 8 characters long.",
  PasswordUpperCase: "Password must contain at least one uppercase letter.",
  PasswordLowerCase: "Password must contain at least one lowercase letter.",
  PasswordNumber: "Password must contain at least one number.",
  PasswordSpecialChar: "Password must contain at least one special character.",
  UpdateProfile: "Update Profile",
  SessionTimeout: "Session Timeout",
  BackupSchedule: "Backup Schedule",
  MaintenanceStartTime: "Maintenance Start Time",
  MaintenanceEndTime: "Maintenance End Time",
  SystemTimezone: "System Timezone",
  UserAccessLog: "User Access Log",
  DefaultLocale: "Default Locale",
  DataRetentionPolicy: "Data Retention Policy",
  NotificationSettings: "Notification Settings",
  AutoLogout: "Auto Logout",
  LoginAttemptsLimit: "Login Attempts Limit",
  System: "System",
  Notifications: "Notifications",


  WelcomeToPansikaOnline: "Welcome to Pansika Online",
  OneStopMarketplace: "Your One-Stop Marketplace for Everything",
  ExploreProductRange: "Explore our extensive range of products designed to meet all your needs.",
  MarketplaceProducts: "Marketplace products",
  StartShopping: "Start Shopping",
  ExclusiveOffers: "Exclusive Offers",
  BestDealsForYou: "Best Deals Just for You",
  DontMissOffers: "Don't miss out on our exclusive offers and discounts available for a limited time.",
  ViewOffers: "View Offers",
  NewArrivals: "New Arrivals",
  DiscoverWhatsNew: "Discover What's New",
  CheckLatestArrivals: "Check out our latest arrivals in various categories tailored for you.",
  SeeNewProducts: "See New Products",

  // Categories
  TopCategories: "Top Categories",
  ShopByCategory: "Shop by Category",
  Electronics: "Electronics",
  LatestGadgets: "Latest gadgets and devices",
  Fashion: "Fashion",
  TrendyClothing: "Trendy clothing and accessories",
  HomeLiving: "Home & Living",
  HomeEssentials: "Essentials for a comfortable home",
  KitchenDining: "Kitchen & Dining",
  QualityKitchenware: "Quality kitchenware for every home chef",

  // Featured Products
  FeaturedProducts: "Featured Products",
  SmartphoneXYZ: "Smartphone XYZ",
  WirelessEarbuds: "Wireless Earbuds",
  FitnessTracker: "Fitness Tracker",
  GamingLaptop: "Gaming Laptop",

  // Features
  WhyChoosePansikaOnline: "Why Choose Pansika Online?",
  FastShipping: "Fast Shipping",
  FastShippingDesc: "Get your orders delivered quickly and efficiently, right to your doorstep.",
  SecurePayments: "Secure Payments",
  SecurePaymentsDesc: "Shop with confidence using our secure payment methods and data protection.",
  QualityAssurance: "Quality Assurance",
  QualityAssuranceDesc: "We ensure that all products meet the highest quality standards before delivery.",

  // Testimonial
  TestimonialQuote: "Shopping at Pansika Online has been a fantastic experience! The variety and quality of products are impressive.",
  TestimonialAuthor: "John Doe",
  TestimonialPosition: "Regular Customer",

  // Call to Action
  JoinOurCommunity: "Join Our Community",
  SubscribeDescription: "Subscribe to our newsletter for updates on the latest products, special offers, and more.",
  SubscribeNow: "Subscribe Now",
  AboutUs: "About Us",
  Categories: "Categories",
  // About Us
  AboutPansikaOnline: "About Pansika Online",
  CommittedToYourExperience: "Committed to Your Shopping Experience",
  PansikaOnlineTeam: "Pansika Online Team",
  OurVision: "Our Vision",
  OurCoreValues: "Our Core Values",
  CustomerSatisfaction: "Customer Satisfaction",
  CustomerSatisfactionDesc: "We prioritize our customers' needs and strive for excellence.",
  Sustainability: "Sustainability",
  SustainabilityDesc: "We are committed to sustainable practices in our operations.",
  CommunityEngagement: "Community Engagement",
  CommunityEngagementDesc: "We actively engage and give back to the communities we serve.",

  // FAQ
  FrequentlyAskedQuestions: "Frequently Asked Questions",
  PaymentMethodsQuestion: "What payment methods do you accept?",
  PaymentMethodsAnswer: "We accept all major credit cards, PayPal, and bank transfers.",
  TrackOrderQuestion: "How can I track my order?",
  TrackOrderAnswer: "You can track your order status in the 'My Orders' section of your account.",
  ReturnPolicyQuestion: "What is your return policy?",
  ReturnPolicyAnswer: "We offer a 30-day return policy on all items. Please refer to our return policy page for more details.",
  InternationalShippingQuestion: "Do you offer international shipping?",
  InternationalShippingAnswer: "Yes, we ship to various countries around the world. Shipping fees may vary based on the destination.",
};
