export const translationKeys = {
    Users: "Utilisateurs",
    StaffStatuses: "Statuts du personnel",
    Genders: "Genres",
    Roles: "Rôles",
    Category: "Catégorie",
    Product: "Produit",
    Modules: "Modules",
    Actions: "Actions",
    Permissions: "Autorisations",
    CompanyConfiguration: "Configuration de l'entreprise",
    SystemConfiguration: "Configuration du système",
    DistributionReport: "Rapport de distribution",
    AccessControl: "Contrôle d'accès",
    Products: "Produits",
    Settings: "Paramètres",
    Reports: "Rapports",
    ProfilePicture: "Photo de profil",
    FullName: "Nom complet",
    Email: "E-mail",
    Password: "Mot de passe",
    PhoneNumber: "Numéro de téléphone",
    DateOfBirth: "Date de naissance",
    RecruitmentDate: "Date de recrutement",
    UserRole: "Rôle utilisateur",
    Status: "Statut",
    Gender: "Genre",
    Description: "Description",
    RoleName: "Nom du rôle",
    CategoryName: "Nom de la catégorie",
    ProductName: "Nom du produit",
    Price: "Prix",
    Images: "Images",
    NumberOfReviews: "Nombre de critiques",
    SalesVolume: "Volume des ventes",
    StockStatus: "État des stocks",
    DiscountPercentage: "Pourcentage de réduction",
    TimeAdded: "Heure d'ajout",
    Brand: "Marque",
    MaterialsUsed: "Matériaux utilisés",
    Color: "Couleur",
    Size: "Taille",
    Features: "Caractéristiques",
    Tags: "Tags",
    WarrantyPeriod: "Période de garantie",
    ManufacturerDetails: "Détails du fabricant",
    ModuleName: "Nom du module",
    Action: "Action",
    Create: "Créer",
    Read: "Lire",
    Update: "Mettre à jour",
    Delete: "Supprimer",
    CompanyLogo: "Logo de l'entreprise",
    CompanyName: "Nom de l'entreprise",
    CompanyGoogleMapLink: "Lien Google Maps de l'entreprise",
    CompanyEmails: "E-mails de l'entreprise",
    CompanyPhoneNumbers: "Numéros de téléphone de l'entreprise",
    CompanySocialMediaLinks: "Liens des réseaux sociaux de l'entreprise",
    CompanyAddress: "Adresse de l'entreprise",
    Location: "Lieu",
    Motto: "Devise",
    SystemLogo: "Logo du système",
    ApplicationName: "Nom de l'application",
    ApplicationVersion: "Version de l'application",
    Language: "Langue",
    GoogleConfiguration: "Configuration Google",
    ClientId: "ID client",
    ClientSecret: "Secret client",
    UserEmail: "E-mail de l'utilisateur",
    UserPassword: "Mot de passe de l'utilisateur",
    AccessToken: "Jeton d'accès",
    RefreshToken: "Jeton de rafraîchissement",
    StripeConfiguration: "Configuration Stripe",
    PublishableKey: "Clé publiable",
    SecretKey: "Clé secrète",
    PaypalConfiguration: "Configuration Paypal",
    JwtConfiguration: "Configuration JWT",
    DatabaseConfiguration: "Configuration de la base de données",
    DatabaseUrl: "URL de la base de données",
    FirebaseConfiguration: "Configuration Firebase",
    ApiKey: "Clé API",
    AuthDomain: "Domaine d'authentification",
    ProjectId: "ID du projet",
    StorageBucket: "Bucket de stockage",
    MessagingSenderId: "Identifiant de l'expéditeur de messages",
    AppId: "ID de l'application",
    TwilioConfiguration: "Configuration Twilio",
    AccountSid: "SID du compte",
    AuthToken: "Jeton d'authentification",
    TwilioNumber: "Numéro Twilio",
    AmazonS3Configuration: "Configuration Amazon S3",
    AccessKeyId: "Clé d'accès ID",
    BucketName: "Nom du bucket",
    OpenAiConfiguration: "Configuration OpenAI",
    LoginPageLayout: "Mise en page de la page de connexion",
    ApplicationDescription: "Description de l'application",
    MaintenanceMessage: "Message de maintenance",
    MaintenanceMode: "Mode maintenance",
    Name: "Nom",
    Link: "Lien",
    Icon: "Icône",
  
    Home: "Accueil",
    Statistics: "Statistiques",
    ExportCSV: "Exporter CSV",
    SelectAll: "Tout sélectionner",
    Ascending: "Ascendant",
    Descending: "Descendant",
    Refresh: "Rafraîchir",
    Filter: "Filtrer",
    Apply: "Appliquer",
    Cancel: "Annuler",
    Reset: "Réinitialiser",
    BulkDelete: "Suppression en masse",
    BulkUpdate: "Mise à jour en masse",
    DownloadCSV: "Télécharger CSV",
    ConfirmBulkDelete: "Confirmer la suppression en masse",
    SelectAction: "Sélectionner une action",
    NoRecordsFound: "Aucun enregistrement trouvé",
    QuickStats: "Statistiques rapides",
    Close: "Fermer",
    AreYouSure: "Êtes-vous sûr ?",
    DoYouWantToLogout: "Voulez-vous vous déconnecter ?",
    Warning: "Avertissement",
    YesLogout: "Oui, déconnectez-moi !",
    LoggedOut: "Déconnecté !",
    ProfileSettings: "Paramètres du profil",
    Settings: "Paramètres",
    Logout: "Déconnexion",
    Role: "Rôle",
    Previous: "Précédent",
    Next: "Suivant",
    Records: "Enregistrements",
    Apply: "Appliquer",
    Submit: "Soumettre",
    Processing: "Traitement...",
    Add: "Ajouter",
    SelectAnOption: "Sélectionner une option",
    Browse: "Parcourir",
    AddFiles: "Ajouter des fichiers",
    Upload: "Télécharger",
    Ok: "Ok",
    QuickActions: "Actions rapides",
    UpdatePassword: "Mettre à jour le mot de passe",
    CurrentPassword: "Mot de passe actuel",
    NewPassword: "Nouveau mot de passe",
    ConfirmNewPassword: "Confirmer le nouveau mot de passe",
    DeleteWarning: "Vous ne pourrez pas annuler cette action !",
    YesDelete: "Oui, supprimez-le !",
    Deleted: "Supprimé !",
    DeleteSuccess: "Votre enregistrement a été supprimé.",
    Error: "Une erreur est survenue !",
    Success: "Succès !",
    DeleteError: "Une erreur s'est produite lors de la suppression de votre enregistrement.",
    BulkUpdateSuccess: "Vos enregistrements ont été mis à jour.",
    BulkUpdateError: "Une erreur est survenue lors de la mise à jour de vos enregistrements.",
    ConfirmBulkDelete: "Confirmer la suppression en masse",
    ConfirmBulkDeleteMessage: "Êtes-vous sûr de vouloir supprimer ces enregistrements ?",
    Cancelled: "Annulé",
    StillLoggedIn: "Vous êtes toujours connecté.",
    Profile: "Profil",
    NoFileChosen: "Aucun fichier choisi",
  };
  