export const translationKeys = {
  Users: "ユーザー",
  StaffStatuses: "スタッフステータス",
  Genders: "性別",
  Roles: "役割",
  Category: "カテゴリー",
  Product: "製品",
  Modules: "モジュール",
  Actions: "アクション",
  Permissions: "権限",
  CompanyConfiguration: "会社の設定",
  SystemConfiguration: "システム設定",
  DistributionReport: "配布レポート",
  AccessControl: "アクセス制御",
  Products: "製品",
  Settings: "設定",
  Reports: "レポート",
  ProfilePicture: "プロフィール写真",
  FullName: "フルネーム",
  Email: "メール",
  Password: "パスワード",
  PhoneNumber: "電話番号",
  DateOfBirth: "生年月日",
  RecruitmentDate: "採用日",
  UserRole: "ユーザーの役割",
  Status: "ステータス",
  Tags: "タグ",
  Description: "説明",
  RoleName: "役割名",
  CategoryName: "カテゴリー名",
  ProductName: "製品名",
  Price: "価格",
  Images: "画像",
  NumberOfReviews: "レビュー数",
  SalesVolume: "販売量",
  StockStatus: "在庫状況",
  DiscountPercentage: "割引率",
  TimeAdded: "追加時間",
  Brand: "ブランド",
  MaterialsUsed: "使用材料",
  Color: "色",
  Size: "サイズ",
  Features: "特徴",
  WarrantyPeriod: "保証期間",
  ManufacturerDetails: "製造者の詳細",
  ModuleName: "モジュール名",
  Action: "アクション",
  Create: "作成",
  Read: "読み取り",
  Update: "更新",
  Delete: "削除",
  CompanyLogo: "会社のロゴ",
  CompanyName: "会社名",
  CompanyGoogleMapLink: "会社のGoogleマップリンク",
  CompanyEmails: "会社のメール",
  CompanyPhoneNumbers: "会社の電話番号",
  CompanySocialMediaLinks: "会社のソーシャルメディアリンク",
  CompanyAddress: "会社の住所",
  Location: "場所",
  Motto: "モットー",
  SystemLogo: "システムロゴ",
  ApplicationName: "アプリケーション名",
  ApplicationVersion: "アプリケーションバージョン",
  Language: "言語",
  GoogleConfiguration: "Google設定",
  ClientId: "クライアントID",
  ClientSecret: "クライアントシークレット",
  UserEmail: "ユーザーのメール",
  UserPassword: "ユーザーのパスワード",
  AccessToken: "アクセストークン",
  RefreshToken: "リフレッシュトークン",
  StripeConfiguration: "Stripe設定",
  PublishableKey: "公開可能キー",
  SecretKey: "シークレットキー",
  PaypalConfiguration: "Paypal設定",
  JwtConfiguration: "JWT設定",
  DatabaseConfiguration: "データベース設定",
  DatabaseUrl: "データベースURL",
  FirebaseConfiguration: "Firebase設定",
  ApiKey: "APIキー",
  AuthDomain: "認証ドメイン",
  ProjectId: "プロジェクトID",
  StorageBucket: "ストレージバケット",
  MessagingSenderId: "メッセージング送信者ID",
  AppId: "アプリID",
  TwilioConfiguration: "Twilio設定",
  AccountSid: "アカウントSID",
  AuthToken: "認証トークン",
  TwilioNumber: "Twilio番号",
  AmazonS3Configuration: "Amazon S3設定",
  AccessKeyId: "アクセスキーID",
  BucketName: "バケット名",
  OpenAiConfiguration: "OpenAI設定",
  LoginPageLayout: "ログインページレイアウト",
  ApplicationDescription: "アプリケーションの説明",
  MaintenanceMessage: "メンテナンスメッセージ",
  MaintenanceMode: "メンテナンスモード",
  Name: "名前",
  Link: "リンク",
  Icon: "アイコン",
  Home: "ホーム",
  Statistics: "統計",
  ExportCSV: "CSVをエクスポート",
  SelectAll: "すべて選択",
  Ascending: "昇順",
  Descending: "降順",
  Refresh: "更新",
  Filter: "フィルター",
  Apply: "適用",
  Cancel: "キャンセル",
  Reset: "リセット",
  BulkDelete: "一括削除",
  BulkUpdate: "一括更新",
  DownloadCSV: "CSVをダウンロード",
  ConfirmBulkDelete: "一括削除の確認",
  SelectAction: "アクションを選択",
  NoRecordsFound: "レコードが見つかりません",
  QuickStats: "クイック統計",
  Close: "閉じる",
  AreYouSure: "本当によろしいですか？",
  DoYouWantToLogout: "ログアウトしますか？",
  Warning: "警告",
  YesLogout: "はい、ログアウトします！",
  LoggedOut: "ログアウトしました！",
  ProfileSettings: "プロフィール設定",
  Settings: "設定",
  Logout: "ログアウト",
  Role: "役割",
  Previous: "前へ",
  Next: "次へ",
  Records: "レコード",
  Submit: "送信",
  Processing: "処理中...",
  Add: "追加",
  SelectAnOption: "オプションを選択",
  Browse: "参照",
  AddFiles: "ファイルを追加",
  Upload: "アップロード",
  Ok: "はい",
  QuickActions: "クイックアクション",
  UpdatePassword: "パスワードを更新",
  CurrentPassword: "現在のパスワード",
  NewPassword: "新しいパスワード",
  ConfirmNewPassword: "新しいパスワードを確認",
  DeleteWarning: "この操作は元に戻せません！",
  YesDelete: "はい、削除します！",
  Deleted: "削除されました！",
  DeleteSuccess: "レコードが削除されました。",
  Error: "エラーが発生しました！",
  Success: "成功！",
  DeleteError: "レコードの削除中にエラーが発生しました。",
  BulkUpdateSuccess: "レコードが更新されました。",
  BulkUpdateError: "レコードの更新中にエラーが発生しました。",
  ConfirmBulkDeleteMessage: "これらのレコードを削除してもよろしいですか？",
  Cancelled: "キャンセルされました",
  StillLoggedIn: "まだログインしています。",
  Profile: "プロフィール",
  NoFileChosen: "ファイルが選択されていません",
  Materials: "材料",
  Shops: "店舗",
  Stores: "店舗",
  ShopName: "店舗名",
  Owner: "所有者",
  Address: "住所",
  ContactNumber: "連絡先番号",
  Shop: "店舗",
  Orders: "注文",
  Sales: "販売",
  OrderNumber: "注文番号",
  Customer: "顧客",
  TotalAmount: "合計金額",
  OrderDate: "注文日",
  Reviews: "レビュー",
  Feedback: "フィードバック",
  Rating: "評価",
  Comment: "コメント",
  ReviewDate: "レビュー日",
  ShopDetails: "店舗の詳細",
  PasswordRequired: "パスワードが必要です。",
  PasswordMinLength: "パスワードは8文字以上でなければなりません。",
  PasswordUpperCase:
    "パスワードには少なくとも1つの大文字が含まれている必要があります。",
  PasswordLowerCase:
    "パスワードには少なくとも1つの小文字が含まれている必要があります。",
  PasswordNumber:
    "パスワードには少なくとも1つの数字が含まれている必要があります。",
  PasswordSpecialChar:
    "パスワードには少なくとも1つの特殊文字が含まれている必要があります。",
  UpdateProfile: "プロフィールを更新",
  SessionTimeout: "セッションタイムアウト",
  BackupSchedule: "バックアップスケジュール",
  MaintenanceStartTime: "メンテナンス開始時間",
  MaintenanceEndTime: "メンテナンス終了時間",
  SystemTimezone: "システムタイムゾーン",
  UserAccessLog: "ユーザーアクセスログ",
  DefaultLocale: "デフォルトのロケール",
  DataRetentionPolicy: "データ保持ポリシー",
  NotificationSettings: "通知設定",
  AutoLogout: "自動ログアウト",
  LoginAttemptsLimit: "ログイン試行制限",
  System: "システム",
  Notifications: "通知",
  WelcomeToPansikaOnline: "パンシカオンラインへようこそ",
  OneStopMarketplace: "すべてのためのワンストップマーケットプレイス",
  ExploreProductRange:
    "あなたのニーズに合わせて設計された幅広い製品を探索してください。",
  MarketplaceProducts: "マーケットプレイス製品",
  StartShopping: "ショッピングを始める",
  ExclusiveOffers: "限定オファー",
  BestDealsForYou: "あなたのためのベストディール",
  DontMissOffers: "期間限定の独占オファーや割引をお見逃しなく。",
  ViewOffers: "オファーを表示",
  NewArrivals: "新入荷",
  DiscoverWhatsNew: "新しいアイテムを発見してください。",
  CheckLatestArrivals:
    "あなたに合わせたさまざまなカテゴリーの最新入荷をチェックしてください。",
  SeeNewProducts: "新製品を見る",

  // カテゴリー
  TopCategories: "トップカテゴリー",
  ShopByCategory: "カテゴリーで購入",
  Electronics: "エレクトロニクス",
  LatestGadgets: "最新のガジェットとデバイス",
  Fashion: "ファッション",
  TrendyClothing: "トレンディな衣類とアクセサリー",
  HomeLiving: "ホーム＆リビング",
  HomeEssentials: "快適な家のための必需品",
  KitchenDining: "キッチン＆ダイニング",
  QualityKitchenware: "すべての家庭料理人のための高品質なキッチンウェア",

  // 特徴的な製品
  FeaturedProducts: "特集商品",
  SmartphoneXYZ: "スマートフォンXYZ",
  WirelessEarbuds: "ワイヤレスイヤフォン",
  FitnessTracker: "フィットネストacker",
  GamingLaptop: "ゲーミングノートパソコン",

  // 特徴
  WhyChoosePansikaOnline: "なぜパンシカオンラインを選ぶのか？",
  FastShipping: "迅速な配送",
  FastShippingDesc: "迅速かつ効率的に、あなたの自宅まで注文を届けます。",
  SecurePayments: "安全な支払い",
  SecurePaymentsDesc:
    "安全な支払い方法とデータ保護を使用して、安心してお買い物を楽しんでください。",
  QualityAssurance: "品質保証",
  QualityAssuranceDesc:
    "すべての製品が最高の品質基準を満たしていることを保証します。",

  // テスティモニアル
  TestimonialQuote:
    "パンシカオンラインでのショッピングは素晴らしい体験でした！製品の多様性と品質には感銘を受けました。",
  TestimonialAuthor: "ジョン・ドー",
  TestimonialPosition: "通常の顧客",

  // 行動を促す
  JoinOurCommunity: "私たちのコミュニティに参加する",
  SubscribeDescription:
    "最新の製品、特別オファー、その他の情報の更新を受け取るために、ニュースレターに登録してください。",
  SubscribeNow: "今すぐ登録",
  AboutUs: "私たちについて",
  Categories: "カテゴリー",
  // 私たちについて
  AboutPansikaOnline: "パンシカオンラインについて",
  CommittedToYourExperience: "あなたのショッピング体験にコミット",
  PansikaOnlineTeam: "パンシカオンラインチーム",
  OurVision: "私たちのビジョン",
  OurCoreValues: "私たちのコアバリュー",
  CustomerSatisfaction: "顧客満足",
  CustomerSatisfactionDesc:
    "私たちはお客様のニーズを最優先し、卓越性を目指します。",
  Sustainability: "持続可能性",
  SustainabilityDesc: "私たちは、業務の持続可能な実践にコミットしています。",
  CommunityEngagement: "コミュニティの関与",
  CommunityEngagementDesc:
    "私たちは、サービスを提供するコミュニティに積極的に関与し、貢献しています。",

  // FAQ
  FrequentlyAskedQuestions: "よくある質問",
  PaymentMethodsQuestion: "どのような支払い方法を受け付けていますか？",
  PaymentMethodsAnswer:
    "主要なクレジットカード、PayPal、銀行振込を受け付けています。",
  TrackOrderQuestion: "注文をどのように追跡できますか？",
  TrackOrderAnswer:
    "アカウントの「マイオーダー」セクションで注文状況を追跡できます。",
  ReturnPolicyQuestion: "返品ポリシーは何ですか？",
  ReturnPolicyAnswer:
    "すべてのアイテムに対して30日間の返品ポリシーを提供しています。詳細については返品ポリシーページをご覧ください。",
  InternationalShippingQuestion: "国際配送は行っていますか？",
  InternationalShippingAnswer:
    "はい、世界各国に配送しています。送料は目的地に応じて異なる場合があります。",
};
