export const translationKeys = {
  Users: "Usuários",
  StaffStatuses: "Status do Funcionário",
  Genders: "Gêneros",
  Roles: "Funções",
  Category: "Categoria",
  Product: "Produto",
  Modules: "Módulos",
  Actions: "Ações",
  Permissions: "Permissões",
  CompanyConfiguration: "Configuração da Empresa",
  SystemConfiguration: "Configuração do Sistema",
  DistributionReport: "Relatório de Distribuição",
  AccessControl: "Controle de Acesso",
  Products: "Produtos",
  Settings: "Configurações",
  Reports: "Relatórios",
  ProfilePicture: "Foto de Perfil",
  FullName: "Nome Completo",
  Email: "Email",
  Password: "Senha",
  PhoneNumber: "Número de Telefone",
  DateOfBirth: "Data de Nascimento",
  RecruitmentDate: "Data de Recrutamento",
  UserRole: "Função do Usuário",
  Status: "Status",
  Gender: "Gênero",
  Description: "Descrição",
  RoleName: "Nome da Função",
  CategoryName: "Nome da Categoria",
  ProductName: "Nome do Produto",
  Price: "Preço",
  Images: "Imagens",
  NumberOfReviews: "Número de Avaliações",
  SalesVolume: "Volume de Vendas",
  StockStatus: "Status do Estoque",
  DiscountPercentage: "Porcentagem de Desconto",
  TimeAdded: "Hora Adicionada",
  Brand: "Marca",
  MaterialsUsed: "Materiais Utilizados",
  Color: "Cor",
  Size: "Tamanho",
  Features: "Características",
  Tags: "Tags",
  WarrantyPeriod: "Período de Garantia",
  ManufacturerDetails: "Detalhes do Fabricante",
  ModuleName: "Nome do Módulo",
  Action: "Ação",
  Create: "Criar",
  Read: "Ler",
  Update: "Atualizar",
  Delete: "Excluir",
  CompanyLogo: "Logotipo da Empresa",
  CompanyName: "Nome da Empresa",
  CompanyGoogleMapLink: "Link do Google Maps da Empresa",
  CompanyEmails: "Emails da Empresa",
  CompanyPhoneNumbers: "Números de Telefone da Empresa",
  CompanySocialMediaLinks: "Links das Redes Sociais da Empresa",
  CompanyAddress: "Endereço da Empresa",
  Location: "Localização",
  Motto: "Lema",
  SystemLogo: "Logotipo do Sistema",
  ApplicationName: "Nome da Aplicação",
  ApplicationVersion: "Versão da Aplicação",
  Language: "Idioma",
  GoogleConfiguration: "Configuração do Google",
  ClientId: "ID do Cliente",
  ClientSecret: "Segredo do Cliente",
  UserEmail: "Email do Usuário",
  UserPassword: "Senha do Usuário",
  AccessToken: "Token de Acesso",
  RefreshToken: "Token de Atualização",
  StripeConfiguration: "Configuração do Stripe",
  PublishableKey: "Chave Publicável",
  SecretKey: "Chave Secreta",
  PaypalConfiguration: "Configuração do Paypal",
  JwtConfiguration: "Configuração do JWT",
  DatabaseConfiguration: "Configuração do Banco de Dados",
  DatabaseUrl: "URL do Banco de Dados",
  FirebaseConfiguration: "Configuração do Firebase",
  ApiKey: "Chave da API",
  AuthDomain: "Domínio de Autenticação",
  ProjectId: "ID do Projeto",
  StorageBucket: "Bucket de Armazenamento",
  MessagingSenderId: "ID do Remetente de Mensagens",
  AppId: "ID do Aplicativo",
  TwilioConfiguration: "Configuração do Twilio",
  AccountSid: "SID da Conta",
  AuthToken: "Token de Autenticação",
  TwilioNumber: "Número Twilio",
  AmazonS3Configuration: "Configuração do Amazon S3",
  AccessKeyId: "ID da Chave de Acesso",
  BucketName: "Nome do Bucket",
  OpenAiConfiguration: "Configuração do OpenAI",
  LoginPageLayout: "Layout da Página de Login",
  ApplicationDescription: "Descrição da Aplicação",
  MaintenanceMessage: "Mensagem de Manutenção",
  MaintenanceMode: "Modo de Manutenção",
  Name: "Nome",
  Link: "Link",
  Icon: "Ícone",

  Home: "Início",
  Statistics: "Estatísticas",
  ExportCSV: "Exportar CSV",
  SelectAll: "Selecionar Tudo",
  Ascending: "Ascendente",
  Descending: "Descendente",
  Refresh: "Atualizar",
  Filter: "Filtrar",
  Apply: "Aplicar",
  Cancel: "Cancelar",
  Reset: "Redefinir",
  BulkDelete: "Excluir em Massa",
  BulkUpdate: "Atualização em Massa",
  DownloadCSV: "Baixar CSV",
  ConfirmBulkDelete: "Confirmar Exclusão em Massa",
  SelectAction: "Selecionar Ação",
  NoRecordsFound: "Nenhum Registro Encontrado",
  QuickStats: "Estatísticas Rápidas",
  Close: "Fechar",
  AreYouSure: "Você tem certeza?",
  DoYouWantToLogout: "Você quer sair?",
  Warning: "Aviso",
  YesLogout: "Sim, Sair!",
  LoggedOut: "Desconectado!",
  ProfileSettings: "Configurações de Perfil",
  Settings: "Configurações",
  Logout: "Sair",
  Role: "Função",
  Previous: "Anterior",
  Next: "Próximo",
  Records: "Registros",
  Apply: "Aplicar",
  Submit: "Enviar",
  Processing: "Processando...",
  Add: "Adicionar",
  SelectAnOption: "Selecione uma opção",
  Browse: "Navegar",
  AddFiles: "Adicionar Arquivos",
  Upload: "Fazer Upload",
  Ok: "Ok",
  QuickActions: "Ações Rápidas",
  UpdatePassword: "Atualizar Senha",
  CurrentPassword: "Senha Atual",
  NewPassword: "Nova Senha",
  ConfirmNewPassword: "Confirmar Nova Senha",
  DeleteWarning: "Você não poderá reverter isso!",
  YesDelete: "Sim, Excluir!",
  Deleted: "Excluído!",
  DeleteSuccess: "Seu registro foi excluído.",
  Error: "Ocorreu um erro!",
  Success: "Sucesso!",
  DeleteError: "Ocorreu um erro ao excluir seu registro.",
  BulkUpdateSuccess: "Seus registros foram atualizados.",
  BulkUpdateError: "Ocorreu um erro ao atualizar seus registros.",
  ConfirmBulkDelete: "Confirmar Exclusão em Massa",
  ConfirmBulkDeleteMessage:
    "Você tem certeza que deseja excluir esses registros?",
  Cancelled: "Cancelado",
  StillLoggedIn: "Você ainda está conectado.",
  Profile: "Perfil",
  NoFileChosen: "Nenhum arquivo escolhido",

  WelcomeToPansikaOnline: "Bem-vindo ao Pansika Online",
  OneStopMarketplace: "Seu mercado único para tudo",
  ExploreProductRange:
    "Explore nossa ampla gama de produtos projetados para atender a todas as suas necessidades.",
  MarketplaceProducts: "Produtos do mercado",
  StartShopping: "Comece a comprar",
  ExclusiveOffers: "Ofertas exclusivas",
  BestDealsForYou: "As melhores ofertas só para você",
  DontMissOffers:
    "Não perca nossas ofertas e descontos exclusivos disponíveis por tempo limitado.",
  ViewOffers: "Ver ofertas",
  NewArrivals: "Novos produtos",
  DiscoverWhatsNew: "Descubra as novidades",
  CheckLatestArrivals:
    "Confira nossas últimas chegadas em várias categorias feitas para você.",
  SeeNewProducts: "Ver novos produtos",

  // Categorias
  TopCategories: "Principais categorias",
  ShopByCategory: "Compre por categoria",
  Electronics: "Eletrônicos",
  LatestGadgets: "Últimos gadgets e dispositivos",
  Fashion: "Moda",
  TrendyClothing: "Roupas e acessórios da moda",
  HomeLiving: "Casa e Vida",
  HomeEssentials: "Essenciais para um lar confortável",
  KitchenDining: "Cozinha e Jantar",
  QualityKitchenware:
    "Utensílios de cozinha de qualidade para cada chef caseiro",

  // Produtos em destaque
  FeaturedProducts: "Produtos em destaque",
  SmartphoneXYZ: "Smartphone XYZ",
  WirelessEarbuds: "Fones de ouvido sem fio",
  FitnessTracker: "Rastreador de fitness",
  GamingLaptop: "Laptop para jogos",

  // Características
  WhyChoosePansikaOnline: "Por que escolher o Pansika Online?",
  FastShipping: "Envio rápido",
  FastShippingDesc:
    "Receba seus pedidos de forma rápida e eficiente, diretamente na sua porta.",
  SecurePayments: "Pagamentos seguros",
  SecurePaymentsDesc:
    "Compre com confiança usando nossos métodos de pagamento seguros e proteção de dados.",
  QualityAssurance: "Garantia de qualidade",
  QualityAssuranceDesc:
    "Garantimos que todos os produtos atendam aos mais altos padrões de qualidade antes da entrega.",

  // Testemunhos
  TestimonialQuote:
    "Comprar no Pansika Online foi uma experiência fantástica! A variedade e qualidade dos produtos são impressionantes.",
  TestimonialAuthor: "John Doe",
  TestimonialPosition: "Cliente regular",

  // Chamada à ação
  JoinOurCommunity: "Junte-se à nossa comunidade",
  SubscribeDescription:
    "Inscreva-se em nossa newsletter para atualizações sobre os últimos produtos, ofertas especiais e muito mais.",
  SubscribeNow: "Inscreva-se agora",
  AboutUs: "Sobre nós",
  Categories: "Categorias",
  // Sobre nós
  AboutPansikaOnline: "Sobre o Pansika Online",
  CommittedToYourExperience: "Comprometidos com a sua experiência de compra",
  PansikaOnlineTeam: "Equipe do Pansika Online",
  OurVision: "Nossa visão",
  OurCoreValues: "Nossos valores fundamentais",
  CustomerSatisfaction: "Satisfação do cliente",
  CustomerSatisfactionDesc:
    "Priorizamos as necessidades de nossos clientes e buscamos a excelência.",
  Sustainability: "Sustentabilidade",
  SustainabilityDesc:
    "Estamos comprometidos com práticas sustentáveis em nossas operações.",
  CommunityEngagement: "Engajamento comunitário",
  CommunityEngagementDesc:
    "Nos envolvemos ativamente e retribuímos às comunidades que atendemos.",

  // Perguntas frequentes
  FrequentlyAskedQuestions: "Perguntas frequentes",
  PaymentMethodsQuestion: "Quais métodos de pagamento vocês aceitam?",
  PaymentMethodsAnswer:
    "Aceitamos todos os principais cartões de crédito, PayPal e transferências bancárias.",
  TrackOrderQuestion: "Como posso rastrear meu pedido?",
  TrackOrderAnswer:
    "Você pode rastrear o status do seu pedido na seção 'Meus pedidos' da sua conta.",
  ReturnPolicyQuestion: "Qual é a sua política de devolução?",
  ReturnPolicyAnswer:
    "Oferecemos uma política de devolução de 30 dias em todos os itens. Consulte nossa página de política de devolução para mais detalhes.",
  InternationalShippingQuestion: "Vocês oferecem envio internacional?",
  InternationalShippingAnswer:
    "Sim, enviamos para vários países ao redor do mundo. As taxas de envio podem variar com base no destino.",
};
