export const translationKeys = {
  Users: "Usuarios",
  StaffStatuses: "Estados del Personal",
  Genders: "Géneros",
  Roles: "Roles",
  Category: "Categoría",
  Product: "Productos",
  Modules: "Módulos",
  Actions: "Acciones",
  Permissions: "Permisos",
  CompanyConfiguration: "Configuración de la Empresa",
  SystemConfiguration: "Configuración del Sistema",
  DistributionReport: "Informe de Distribución",
  AccessControl: "Control de Acceso",
  Products: "Productos",
  Settings: "Configuraciones",
  Reports: "Informes",
  ProfilePicture: "Foto de Perfil",
  FullName: "Nombre Completo",
  Email: "Correo Electrónico",
  Password: "Contraseña",
  PhoneNumber: "Número de Teléfono",
  DateOfBirth: "Fecha de Nacimiento",
  RecruitmentDate: "Fecha de Reclutamiento",
  UserRole: "Rol de Usuario",
  Status: "Estado",
  Tags: "Etiquetas",
  Description: "Descripción",
  RoleName: "Nombre del Rol",
  CategoryName: "Nombre de la Categoría",
  ProductName: "Nombre del Producto",
  Price: "Precio",
  Images: "Imágenes",
  NumberOfReviews: "Número de Reseñas",
  SalesVolume: "Volumen de Ventas",
  StockStatus: "Estado del Stock",
  DiscountPercentage: "Porcentaje de Descuento",
  TimeAdded: "Hora Agregada",
  Brand: "Marca",
  MaterialsUsed: "Materiales Usados",
  Color: "Color",
  Size: "Tamaño",
  Features: "Características",
  WarrantyPeriod: "Período de Garantía",
  ManufacturerDetails: "Detalles del Fabricante",
  ModuleName: "Nombre del Módulo",
  Action: "Acción",
  Create: "Crear",
  Read: "Leer",
  Update: "Actualizar",
  Delete: "Eliminar",
  CompanyLogo: "Logotipo de la Empresa",
  CompanyName: "Nombre de la Empresa",
  CompanyGoogleMapLink: "Enlace de Google Maps de la Empresa",
  CompanyEmails: "Correos Electrónicos de la Empresa",
  CompanyPhoneNumbers: "Números de Teléfono de la Empresa",
  CompanySocialMediaLinks: "Enlaces de Redes Sociales de la Empresa",
  CompanyAddress: "Dirección de la Empresa",
  Location: "Ubicación",
  Motto: "Lema",
  SystemLogo: "Logotipo del Sistema",
  ApplicationName: "Nombre de la Aplicación",
  ApplicationVersion: "Versión de la Aplicación",
  Language: "Idioma",
  GoogleConfiguration: "Configuración de Google",
  ClientId: "ID de Cliente",
  ClientSecret: "Secreto de Cliente",
  UserEmail: "Correo Electrónico del Usuario",
  UserPassword: "Contraseña del Usuario",
  AccessToken: "Token de Acceso",
  RefreshToken: "Token de Actualización",
  StripeConfiguration: "Configuración de Stripe",
  PublishableKey: "Clave Publicable",
  SecretKey: "Clave Secreta",
  PaypalConfiguration: "Configuración de Paypal",
  JwtConfiguration: "Configuración de JWT",
  DatabaseConfiguration: "Configuración de Base de Datos",
  DatabaseUrl: "URL de la Base de Datos",
  FirebaseConfiguration: "Configuración de Firebase",
  ApiKey: "Clave de API",
  AuthDomain: "Dominio de Autenticación",
  ProjectId: "ID de Proyecto",
  StorageBucket: "Cubo de Almacenamiento",
  MessagingSenderId: "ID de Enviador de Mensajes",
  AppId: "ID de Aplicación",
  TwilioConfiguration: "Configuración de Twilio",
  AccountSid: "SID de Cuenta",
  AuthToken: "Token de Autenticación",
  TwilioNumber: "Número de Twilio",
  AmazonS3Configuration: "Configuración de Amazon S3",
  AccessKeyId: "ID de Clave de Acceso",
  BucketName: "Nombre del Cubo",
  OpenAiConfiguration: "Configuración de OpenAI",
  LoginPageLayout: "Diseño de Página de Inicio de Sesión",
  ApplicationDescription: "Descripción de la Aplicación",
  MaintenanceMessage: "Mensaje de Mantenimiento",
  MaintenanceMode: "Modo de Mantenimiento",
  Name: "Nombre",
  Link: "Enlace",
  Icon: "Ícono",
  Home: "Inicio",
  Statistics: "Estadísticas",
  ExportCSV: "Exportar CSV",
  SelectAll: "Seleccionar Todo",
  Ascending: "Ascendente",
  Descending: "Descendente",
  Refresh: "Actualizar",
  Filter: "Filtrar",
  Apply: "Aplicar",
  Cancel: "Cancelar",
  Reset: "Restablecer",
  BulkDelete: "Eliminar en Masa",
  BulkUpdate: "Actualizar en Masa",
  DownloadCSV: "Descargar CSV",
  ConfirmBulkDelete: "Confirmar Eliminación en Masa",
  SelectAction: "Seleccionar Acción",
  NoRecordsFound: "No se Encontraron Registros",
  QuickStats: "Estadísticas Rápidas",
  Close: "Cerrar",
  AreYouSure: "¿Estás seguro?",
  DoYouWantToLogout: "¿Quieres cerrar sesión?",
  Warning: "Advertencia",
  YesLogout: "¡Sí, cierra mi sesión!",
  LoggedOut: "¡Cerrado!",
  ProfileSettings: "Configuraciones del Perfil",
  Settings: "Configuraciones",
  Logout: "Cerrar Sesión",
  Role: "Rol",
  Previous: "Anterior",
  Next: "Siguiente",
  Records: "Registros",
  Submit: "Enviar",
  Processing: "Procesando...",
  Add: "Agregar",
  SelectAnOption: "Selecciona una opción",
  Browse: "Explorar",
  AddFiles: "Agregar Archivos",
  Upload: "Subir",
  Ok: "Aceptar",
  QuickActions: "Acciones Rápidas",
  UpdatePassword: "Actualizar Contraseña",
  CurrentPassword: "Contraseña Actual",
  NewPassword: "Nueva Contraseña",
  ConfirmNewPassword: "Confirmar Nueva Contraseña",
  DeleteWarning: "¡No podrás revertir esto!",
  YesDelete: "¡Sí, elimínalo!",
  Deleted: "¡Eliminado!",
  DeleteSuccess: "Tu registro ha sido eliminado.",
  Error: "¡Ocurrió un error!",
  Success: "¡Éxito!",
  DeleteError: "¡Ocurrió un error al eliminar tu registro!",
  BulkUpdateSuccess: "Tus registros han sido actualizados.",
  BulkUpdateError: "¡Ocurrió un error al actualizar tus registros!",
  ConfirmBulkDeleteMessage:
    "¿Estás seguro de que deseas eliminar estos registros?",
  Cancelled: "Cancelado",
  StillLoggedIn: "Sigues conectado.",
  Profile: "Perfil",
  NoFileChosen: "No se ha elegido ningún archivo",
  Materials: "Materiales",
  Shops: "Tiendas",
  Stores: "Tiendas",
  ShopName: "Nombre de la Tienda",
  Owner: "Propietario",
  Address: "Dirección",
  ContactNumber: "Número de Contacto",
  Shop: "Tienda",
  Orders: "Órdenes",
  Sales: "Ventas",
  OrderNumber: "Número de Orden",
  Customer: "Cliente",
  TotalAmount: "Monto Total",
  OrderDate: "Fecha de Orden",
  Reviews: "Reseñas",
  Feedback: "Comentarios",
  Rating: "Calificación",
  Comment: "Comentario",
  ReviewDate: "Fecha de Reseña",
  ShopDetails: "Detalles de la Tienda",
  PasswordRequired: "Se requiere contraseña.",
  PasswordMinLength: "La contraseña debe tener al menos 8 caracteres.",
  PasswordUpperCase:
    "La contraseña debe contener al menos una letra mayúscula.",
  PasswordLowerCase:
    "La contraseña debe contener al menos una letra minúscula.",
  PasswordNumber: "La contraseña debe contener al menos un número.",
  PasswordSpecialChar:
    "La contraseña debe contener al menos un carácter especial.",
  UpdateProfile: "Actualizar Perfil",
  SessionTimeout: "Tiempo de Sesión Agotado",
  BackupSchedule: "Horario de Respaldo",
  MaintenanceStartTime: "Hora de Inicio de Mantenimiento",
  MaintenanceEndTime: "Hora de Fin de Mantenimiento",
  SystemTimezone: "Zona Horaria del Sistema",
  UserAccessLog: "Registro de Acceso de Usuario",
  DefaultLocale: "Configuración Regional Predeterminada",
  DataRetentionPolicy: "Política de Retención de Datos",
  NotificationSettings: "Configuraciones de Notificaciones",
  AutoLogout: "Cierre de Sesión Automático",
  LoginAttemptsLimit: "Límite de Intentos de Inicio de Sesión",
  System: "Sistema",
  Notifications: "Notificaciones",

  WelcomeToPansikaOnline: "Bienvenido a Pansika Online",
  OneStopMarketplace: "Tu mercado único para todo",
  ExploreProductRange:
    "Explora nuestra extensa gama de productos diseñados para satisfacer todas tus necesidades.",
  MarketplaceProducts: "Productos del mercado",
  StartShopping: "Comienza a comprar",
  ExclusiveOffers: "Ofertas exclusivas",
  BestDealsForYou: "Las mejores ofertas solo para ti",
  DontMissOffers:
    "No te pierdas nuestras ofertas exclusivas y descuentos disponibles por tiempo limitado.",
  ViewOffers: "Ver ofertas",
  NewArrivals: "Nuevos productos",
  DiscoverWhatsNew: "Descubre las novedades",
  CheckLatestArrivals:
    "Consulta nuestras últimas llegadas en varias categorías diseñadas para ti.",
  SeeNewProducts: "Ver nuevos productos",

  // Categorías
  TopCategories: "Principales categorías",
  ShopByCategory: "Compra por categoría",
  Electronics: "Electrónica",
  LatestGadgets: "Últimos gadgets y dispositivos",
  Fashion: "Moda",
  TrendyClothing: "Ropa y accesorios de moda",
  HomeLiving: "Hogar y vida",
  HomeEssentials: "Esenciales para un hogar cómodo",
  KitchenDining: "Cocina y comedor",
  QualityKitchenware: "Utensilios de cocina de calidad para cada chef casero",

  // Productos destacados
  FeaturedProducts: "Productos destacados",
  SmartphoneXYZ: "Smartphone XYZ",
  WirelessEarbuds: "Auriculares inalámbricos",
  FitnessTracker: "Rastreador de fitness",
  GamingLaptop: "Laptop para juegos",

  // Características
  WhyChoosePansikaOnline: "¿Por qué elegir Pansika Online?",
  FastShipping: "Envío rápido",
  FastShippingDesc:
    "Recibe tus pedidos rápidamente y de manera eficiente, directamente en tu puerta.",
  SecurePayments: "Pagos seguros",
  SecurePaymentsDesc:
    "Compra con confianza usando nuestros métodos de pago seguros y protección de datos.",
  QualityAssurance: "Garantía de calidad",
  QualityAssuranceDesc:
    "Aseguramos que todos los productos cumplan con los más altos estándares de calidad antes de la entrega.",

  // Testimonios
  TestimonialQuote:
    "¡Comprar en Pansika Online ha sido una experiencia fantástica! La variedad y calidad de los productos son impresionantes.",
  TestimonialAuthor: "John Doe",
  TestimonialPosition: "Cliente habitual",

  // Llamado a la acción
  JoinOurCommunity: "Únete a nuestra comunidad",
  SubscribeDescription:
    "Suscríbete a nuestro boletín para recibir actualizaciones sobre los últimos productos, ofertas especiales y más.",
  SubscribeNow: "Suscríbete ahora",
  AboutUs: "Acerca de nosotros",
  Categories: "Categorías",
  // Acerca de nosotros
  AboutPansikaOnline: "Acerca de Pansika Online",
  CommittedToYourExperience: "Comprometidos con tu experiencia de compra",
  PansikaOnlineTeam: "Equipo de Pansika Online",
  OurVision: "Nuestra visión",
  OurCoreValues: "Nuestros valores fundamentales",
  CustomerSatisfaction: "Satisfacción del cliente",
  CustomerSatisfactionDesc:
    "Priorizamos las necesidades de nuestros clientes y buscamos la excelencia.",
  Sustainability: "Sostenibilidad",
  SustainabilityDesc:
    "Estamos comprometidos con prácticas sostenibles en nuestras operaciones.",
  CommunityEngagement: "Compromiso comunitario",
  CommunityEngagementDesc:
    "Nos involucramos activamente y devolvemos a las comunidades que servimos.",

  // Preguntas frecuentes
  FrequentlyAskedQuestions: "Preguntas frecuentes",
  PaymentMethodsQuestion: "¿Qué métodos de pago aceptan?",
  PaymentMethodsAnswer:
    "Aceptamos todas las principales tarjetas de crédito, PayPal y transferencias bancarias.",
  TrackOrderQuestion: "¿Cómo puedo rastrear mi pedido?",
  TrackOrderAnswer:
    "Puedes rastrear el estado de tu pedido en la sección 'Mis pedidos' de tu cuenta.",
  ReturnPolicyQuestion: "¿Cuál es su política de devoluciones?",
  ReturnPolicyAnswer:
    "Ofrecemos una política de devolución de 30 días en todos los artículos. Por favor, consulta nuestra página de política de devoluciones para más detalles.",
  InternationalShippingQuestion: "¿Ofrecen envío internacional?",
  InternationalShippingAnswer:
    "Sí, enviamos a varios países de todo el mundo. Las tarifas de envío pueden variar según el destino.",
};
