export const translationKeys = {
    Users: "Watumiaji",
    StaffStatuses: "Hali za Wafanyakazi",
    Genders: "Jinsia",
    Roles: "Majukumu",
    Category: "Kategoria",
    Product: "Bidhaa",
    Modules: "Moduli",
    Actions: "Vitendo",
    Permissions: "Ruhusa",
    CompanyConfiguration: "Usanidi wa Kampuni",
    SystemConfiguration: "Usanidi wa Mfumo",
    DistributionReport: "Ripoti ya Usambazaji",
    AccessControl: "Udhibiti wa Ufikiaji",
    Products: "Bidhaa",
    Settings: "Mipangilio",
    Reports: "Ripoti",
    ProfilePicture: "Picha ya Profaili",
    FullName: "Jina Kamili",
    Email: "Barua Pepe",
    Password: "Nenosiri",
    PhoneNumber: "Nambari ya Simu",
    DateOfBirth: "Tarehe ya Kuzaliwa",
    RecruitmentDate: "Tarehe ya Kuajiriwa",
    UserRole: "Jukumu la Mtumiaji",
    Status: "Hali",
    Gender: "Jinsia",
    Description: "Maelezo",
    RoleName: "Jina la Jukumu",
    CategoryName: "Jina la Kategoria",
    ProductName: "Jina la Bidhaa",
    Price: "Bei",
    Images: "Picha",
    NumberOfReviews: "Idadi ya Mapitio",
    SalesVolume: "Kiasi cha Mauzo",
    StockStatus: "Hali ya Hisa",
    DiscountPercentage: "Asilimia ya Punguzo",
    TimeAdded: "Wakati Uliowekwa",
    Brand: "Chapa",
    MaterialsUsed: "Vifaa Vilivyotumika",
    Color: "Rangi",
    Size: "Ukubwa",
    Features: "Vipengele",
    Tags: "Vitambulisho",
    WarrantyPeriod: "Muda wa Udhamini",
    ManufacturerDetails: "Maelezo ya Mtengenezaji",
    ModuleName: "Jina la Moduli",
    Action: "Kitendo",
    Create: "Unda",
    Read: "Soma",
    Update: "Sasisha",
    Delete: "Futa",
    CompanyLogo: "Nembo ya Kampuni",
    CompanyName: "Jina la Kampuni",
    CompanyGoogleMapLink: "Kiungo cha Ramani ya Google cha Kampuni",
    CompanyEmails: "Barua Pepe za Kampuni",
    CompanyPhoneNumbers: "Nambari za Simu za Kampuni",
    CompanySocialMediaLinks: "Viungo vya Mitandao ya Kijamii vya Kampuni",
    CompanyAddress: "Anwani ya Kampuni",
    Location: "Mahali",
    Motto: "Kauli Mbiu",
    SystemLogo: "Nembo ya Mfumo",
    ApplicationName: "Jina la Programu",
    ApplicationVersion: "Toleo la Programu",
    Language: "Lugha",
    GoogleConfiguration: "Usanidi wa Google",
    ClientId: "Kitambulisho cha Mteja",
    ClientSecret: "Siri ya Mteja",
    UserEmail: "Barua Pepe ya Mtumiaji",
    UserPassword: "Nenosiri la Mtumiaji",
    AccessToken: "Tokeni ya Ufikiaji",
    RefreshToken: "Tokeni ya Kusasisha",
    StripeConfiguration: "Usanidi wa Stripe",
    PublishableKey: "Funguo ya Kuchapisha",
    SecretKey: "Funguo ya Siri",
    PaypalConfiguration: "Usanidi wa Paypal",
    JwtConfiguration: "Usanidi wa JWT",
    DatabaseConfiguration: "Usanidi wa Hifadhidata",
    DatabaseUrl: "URL ya Hifadhidata",
    FirebaseConfiguration: "Usanidi wa Firebase",
    ApiKey: "Funguo ya API",
    AuthDomain: "Eneo la Uthibitishaji",
    ProjectId: "Kitambulisho cha Mradi",
    StorageBucket: "Kibukia cha Hifadhi",
    MessagingSenderId: "Kitambulisho cha Mtumaji wa Ujumbe",
    AppId: "Kitambulisho cha Programu",
    TwilioConfiguration: "Usanidi wa Twilio",
    AccountSid: "SID ya Akaunti",
    AuthToken: "Tokeni ya Uthibitishaji",
    TwilioNumber: "Nambari ya Twilio",
    AmazonS3Configuration: "Usanidi wa Amazon S3",
    AccessKeyId: "Kitambulisho cha Funguo ya Ufikiaji",
    BucketName: "Jina la Kibukia",
    OpenAiConfiguration: "Usanidi wa OpenAI",
    LoginPageLayout: "Mpangilio wa Ukurasa wa Kuingia",
    ApplicationDescription: "Maelezo ya Programu",
    MaintenanceMessage: "Ujumbe wa Matengenezo",
    MaintenanceMode: "Hali ya Matengenezo",
    Name: "Jina",
    Link: "Kiungo",
    Icon: "Aikoni",
  
    Home: "Nyumbani",
    Statistics: "Takwimu",
    ExportCSV: "Hamisha CSV",
    SelectAll: "Chagua Zote",
    Ascending: "Kupanda",
    Descending: "Kushuka",
    Refresh: "Fanya upya",
    Filter: "Chuja",
    Apply: "Tumia",
    Cancel: "Ghairi",
    Reset: "Weka Upya",
    BulkDelete: "Futa kwa Wingi",
    BulkUpdate: "Sasisha kwa Wingi",
    DownloadCSV: "Pakua CSV",
    ConfirmBulkDelete: "Thibitisha Kufuta kwa Wingi",
    SelectAction: "Chagua Kitendo",
    NoRecordsFound: "Hakuna Rekodi Zilizopatikana",
    QuickStats: "Takwimu za Haraka",
    Close: "Funga",
    AreYouSure: "Una uhakika?",
    DoYouWantToLogout: "Unataka kutoka?",
    Warning: "Onyo",
    YesLogout: "Ndio, Nitoke!",
    LoggedOut: "Umetoka!",
    ProfileSettings: "Mipangilio ya Profaili",
    Settings: "Mipangilio",
    Logout: "Toka",
    Role: "Jukumu",
    Previous: "Kabla",
    Next: "Ifuatayo",
    Records: "Rekodi",
    Apply: "Tumia",
    Submit: "Wasilisha",
    Processing: "Inachakata...",
    Add: "Ongeza",
    SelectAnOption: "Chagua Chaguo",
    Browse: "Vinjari",
    AddFiles: "Ongeza Faili",
    Upload: "Pakia",
    Ok: "Sawa",
    QuickActions: "Vitendo vya Haraka",
    UpdatePassword: "Sasisha Nenosiri",
    CurrentPassword: "Nenosiri la Sasa",
    NewPassword: "Nenosiri Jipya",
    ConfirmNewPassword: "Thibitisha Nenosiri Jipya",
    DeleteWarning: "Hutaweza Kurejesha Hili!",
    YesDelete: "Ndio, Futa!",
    Deleted: "Imefutwa!",
    DeleteSuccess: "Rekodi yako imefutwa.",
    Error: "Hitilafu imetokea!",
    Success: "Mafanikio!",
    DeleteError: "Hitilafu ilitokea wakati wa kufuta rekodi yako.",
    BulkUpdateSuccess: "Rekodi zako zimesasishwa.",
    BulkUpdateError: "Hitilafu ilitokea wakati wa kusasisha rekodi zako.",
    ConfirmBulkDelete: "Thibitisha Kufuta kwa Wingi",
    ConfirmBulkDeleteMessage: "Una uhakika unataka kufuta rekodi hizi?",
    Cancelled: "Imeghairiwa",
    StillLoggedIn: "Bado umeingia.",
    Profile: "Profaili",
    NoFileChosen: "Hakuna faili iliyochaguliwa",
  };
  