export const translationKeys = {
  Users: "Ogwiritsa ntchito",
  StaffStatuses: "Mavuto a antchito",
  Genders: "Ziwalo",
  Roles: "Maudindo",
  Category: "Gulu",
  Product: "Katundu",
  Modules: "Zigawo",
  Actions: "Zochita",
  Permissions: "Zololedwa",
  CompanyConfiguration: "Kasankhidwe ka kampani",
  SystemConfiguration: "Kasankhidwe ka dongosolo",
  DistributionReport: "Lipoti la kugawa",
  AccessControl: "Ulamuliro wolowa",
  Products: "Katundu",
  Settings: "Zokonza",
  Reports: "Malipoti",
  ProfilePicture: "Chithunzi cha munthu",
  FullName: "Dzina lonse",
  Email: "Imelo",
  Password: "Mawu achinsinsi",
  PhoneNumber: "Nambala ya foni",
  DateOfBirth: "Tsiku lobadwa",
  RecruitmentDate: "Tsiku lolemba ntchito",
  UserRole: "Udindo wa ogwiritsa ntchito",
  Status: "Mkhalidwe",
  Gender: "Chiwalo",
  Description: "Kulongosola",
  RoleName: "Dzina la udindo",
  CategoryName: "Dzina la gulu",
  ProductName: "Dzina la katundu",
  Price: "Mtengo",
  Images: "Zithunzi",
  NumberOfReviews: "Chiwerengero cha malingaliro",
  SalesVolume: "Kuchuluka kwa malonda",
  StockStatus: "Mkhalidwe wa katundu",
  DiscountPercentage: "Peresenti ya kuchotsera",
  TimeAdded: "Nthawi yowonjezera",
  Brand: "Mtundu",
  MaterialsUsed: "Zipangizo zogwiritsira ntchito",
  Color: "Mtundu",
  Size: "Kukula",
  Features: "Zinthu zapadera",
  Tags: "Zizindikiro",
  WarrantyPeriod: "Nthawi ya chitsimikizo",
  ManufacturerDetails: "Tsatanetsatane wa opanga",
  ModuleName: "Dzina la gawo",
  Action: "Chochita",
  Create: "Kupanga",
  Read: "Kuwerenga",
  Update: "Kusintha",
  Delete: "Kufafaniza",
  CompanyLogo: "Chizindikiro cha kampani",
  CompanyName: "Dzina la kampani",
  CompanyGoogleMapLink: "Ulalo wa Google Map wa kampani",
  CompanyEmails: "Maimelo a kampani",
  CompanyPhoneNumbers: "Manambala a foni a kampani",
  CompanySocialMediaLinks: "Maulalo a social media a kampani",
  CompanyAddress: "Adilesi ya kampani",
  Location: "Malo",
  Motto: "Mawu otsogolera",
  SystemLogo: "Chizindikiro cha dongosolo",
  ApplicationName: "Dzina la pulogalamu",
  ApplicationVersion: "Mtundu wa pulogalamu",
  Language: "Chiyankhulo",
  GoogleConfiguration: "Kasankhidwe ka Google",
  ClientId: "ID ya kasitomala",
  ClientSecret: "Chinsinsi cha kasitomala",
  UserEmail: "Imelo ya ogwiritsa ntchito",
  UserPassword: "Mawu achinsinsi a ogwiritsa ntchito",
  AccessToken: "Chizindikiro cholowa",
  RefreshToken: "Chizindikiro chokonzanso",
  StripeConfiguration: "Kasankhidwe ka Stripe",
  PublishableKey: "Kiyi yosindikizika",
  SecretKey: "Kiyi yachinsinsi",
  PaypalConfiguration: "Kasankhidwe ka Paypal",
  JwtConfiguration: "Kasankhidwe ka JWT",
  DatabaseConfiguration: "Kasankhidwe ka database",
  DatabaseUrl: "URL ya database",
  FirebaseConfiguration: "Kasankhidwe ka Firebase",
  ApiKey: "Kiyi ya API",
  AuthDomain: "Dera lovomerezeka",
  ProjectId: "ID ya pulojekiti",
  StorageBucket: "Bucket yosungiramo",
  MessagingSenderId: "ID yotumiza mauthenga",
  AppId: "ID ya pulogalamu",
  TwilioConfiguration: "Kasankhidwe ka Twilio",
  AccountSid: "SID ya akaunti",
  AuthToken: "Chizindikiro chovomerezeka",
  TwilioNumber: "Nambala ya Twilio",
  AmazonS3Configuration: "Kasankhidwe ka Amazon S3",
  AccessKeyId: "ID ya kiyi yolowa",
  BucketName: "Dzina la bucket",
  OpenAiConfiguration: "Kasankhidwe ka OpenAI",
  LoginPageLayout: "Kasankhidwe ka tsamba lolowera",
  ApplicationDescription: "Kulongosola kwa pulogalamu",
  MaintenanceMessage: "Uthenga wa kukonza",
  MaintenanceMode: "Njira yokonzera",
  Name: "Dzina",
  Link: "Ulalo",
  Icon: "Chizindikiro",

  Home: "Kunyumba",
  Statistics: "Ziwerengero",
  ExportCSV: "Kutulutsa CSV",
  SelectAll: "Sankha zonse",
  Ascending: "Kukwera",
  Descending: "Kutsika",
  Refresh: "Konza",
  Filter: "Sefa",
  Apply: "Gwiritsani ntchito",
  Cancel: "Letsani",
  Reset: "Bwezeretsa",
  BulkDelete: "Fafanizani zambiri",
  BulkUpdate: "Sinthani zambiri",
  DownloadCSV: "Tsitsani CSV",
  ConfirmBulkDelete: "Tsimikizani kufafaniza zambiri",
  SelectAction: "Sankhani chochita",
  NoRecordsFound: "Palibe zolemba zopezeka",
  QuickStats: "Ziwerengero zachangu",
  Close: "Tsekani",
  AreYouSure: "Kodi muli otsimikiza?",
  DoYouWantToLogout: "Kodi mukufuna kutuluka?",
  Warning: "Chenjezo",
  YesLogout: "Inde, ndichoke!",
  LoggedOut: "Mwatuluka!",
  ProfileSettings: "Zokhuzana ndi mbiri",
  Settings: "Zokonza",
  Logout: "Tulukani",
  Role: "Udindo",
  Previous: "Zapitazo",
  Next: "Zotsatira",
  Records: "Zolemba",
  Apply: "Gwiritsani ntchito",
  Submit: "Tumizani",
  Processing: "Tikukonza...",
  Add: "Onjezani",
  SelectAnOption: "Sankhani chosankha",
  Browse: "Fufuzani",
  AddFiles: "Onjezani mafayilo",
  Upload: "Kwezani",
  Ok: "Chabwino",
  QuickActions: "Zochita mwachangu",
  UpdatePassword: "Sinthani mawu achinsinsi",
  CurrentPassword: "Mawu achinsinsi amakono",
  NewPassword: "Mawu achinsinsi atsopano",
  ConfirmNewPassword: "Tsimikizani mawu achinsinsi atsopano",
  DeleteWarning: "Simungathe kubwezeretsa izi!",
  YesDelete: "Inde, fafanizani!",
  Deleted: "Zafafanizidwa!",
  DeleteSuccess: "Zolemba zanu zafafanizidwa.",
  Error: "Pali vuto!",
  Success: "Zapambana!",
  DeleteError: "Pali vuto pofafaniza zolemba zanu.",
  BulkUpdateSuccess: "Zolemba zanu zakonzedwa.",
  BulkUpdateError: "Pali vuto pokonza zolemba zanu zambiri.",
  ConfirmBulkDelete: "Tsimikizani kufafaniza zambiri",
  ConfirmBulkDeleteMessage:
    "Kodi muli otsimikiza kuti mukufuna kufafaniza zolemba izi?",
  Cancelled: "Zalekedwa",
  StillLoggedIn: "Mudakali mulowa.",
  Profile: "Mbiri",
  NoFileChosen: "Palibe fayilo yosankhidwa",

  WelcomeToPansikaOnline: "Tikutumbika ku Pansika Online",
  OneStopMarketplace: "Msika wako umodzi wopangira zinthu zonse",
  ExploreProductRange:
    "Fufuzani zinthu zathu zambiri zomwe zidakonzedwa kuti zikwaniritse zosowa zanu zonse.",
  MarketplaceProducts: "Zinthu za msika",
  StartShopping: "Yambani kugula",
  ExclusiveOffers: "Zopereka zapadera",
  BestDealsForYou: "Zokulitsa zabwino kwambiri zongokuthandizani",
  DontMissOffers:
    "Musapuse zomwe tili nazo zapadera komanso zotsika mtengo zomwe zili zochepa.",
  ViewOffers: "Onani zopereka",
  NewArrivals: "Zatsopano",
  DiscoverWhatsNew: "Fufuzani zomwe zatsopano",
  CheckLatestArrivals:
    "Onani zomwe zatsopano mu zigawo zosiyanasiyana zomwe zidakonzedwa kwa inu.",
  SeeNewProducts: "Onani Zatsopano",

  // Magulu
  TopCategories: "Magulu Apamwamba",
  ShopByCategory: "Gulani pogwiritsa ntchito gulu",
  Electronics: "Zida zamagetsi",
  LatestGadgets: "Zida zatsopano ndi zida",
  Fashion: "Chimwene",
  TrendyClothing: "Zovala ndi zinthu zatsopano",
  HomeLiving: "Nyumba & Moyo",
  HomeEssentials: "Zofunikira za nyumba yokongola",
  KitchenDining: "Kicheni & Kusankha",
  QualityKitchenware:
    "Zida zapamwamba za kicheni kwa aliyense wochita ziphuphu",

  // Zinthu zapamwamba
  FeaturedProducts: "Zinthu Zapamwamba",
  SmartphoneXYZ: "Smartphone XYZ",
  WirelessEarbuds: "Ma earbud osavuta",
  FitnessTracker: "Zida za kuyang'anira thanzi",
  GamingLaptop: "Laptop yama games",

  // Zambiri
  WhyChoosePansikaOnline: "N'chifukwa chiyani kusankha Pansika Online?",
  FastShipping: "Kutumiza mwachangu",
  FastShippingDesc:
    "Perekani ma oda anu mwachangu komanso mwachangu, mwachindunji ku tsamba lanu.",
  SecurePayments: "Malipiro otetezeka",
  SecurePaymentsDesc:
    "Gulani ndi chikhulupiliro pogwiritsa ntchito njira zathu zotetezedwa komanso chitetezo cha data.",
  QualityAssurance: "Chitsimikizo cha Khalidwe",
  QualityAssuranceDesc:
    "Timatsimikizira kuti zinthu zonse zikugwirizana ndi mfundo zatsopano zapamwamba musanatumize.",

  // Zotsatira
  TestimonialQuote:
    "Kugula ku Pansika Online kwakhala chithandizo chabwino! Kusiyana komanso khalidwe la zinthu ndi zosangalatsa.",
  TestimonialAuthor: "John Doe",
  TestimonialPosition: "Makasitomala wochita bwino",

  // Kuitana kwa Action
  JoinOurCommunity: "Lowani mu bungwe lathu",
  SubscribeDescription:
    "Dziwani za zinthu zatsopano, zotsatsa zapadera, ndi zambiri.",
  SubscribeNow: "Lembani Tsopano",
  AboutUs: "Zokhudza ife",
  Categories: "Magulu",
  // Zokhudza ife
  AboutPansikaOnline: "Zokhudza Pansika Online",
  CommittedToYourExperience: "Tikhala okonzeka kwa Moyo Wanu",
  PansikaOnlineTeam: "Gulu la Pansika Online",
  OurVision: "Cholinga Chathu",
  OurCoreValues: "Zofunikira Zathu",
  CustomerSatisfaction: "Kuchita bwino kwa Makasitomala",
  CustomerSatisfactionDesc:
    "Tikulimbikira kufuna zofunikira za makasitomala athu.",
  Sustainability: "Kukhala kwanthawi yaitali",
  SustainabilityDesc:
    "Tikugwira ntchito za njira zolemekezeka m'ntchito zathu.",
  CommunityEngagement: "Kukhala pamodzi ndi anthu",
  CommunityEngagementDesc:
    "Timakhala ndi mwayi wokuthandizani ndi kubwerera ku anthu omwe tikhala nawo.",

  // Mafunso Ofunika
  FrequentlyAskedQuestions: "Mafunso Ofunika",
  PaymentMethodsQuestion: "Kodi mukulandira njira ziti zolipira?",
  PaymentMethodsAnswer:
    "Tikulandira makhadi onse apamwamba, PayPal, ndi kutumiza kwa banki.",
  TrackOrderQuestion: "Ndingatani kutsatira maoda anga?",
  TrackOrderAnswer:
    "Mungathe kutsatira kuchita kwa maoda anu mu 'Maoda Anga' gawo la akaunti yanu.",
  ReturnPolicyQuestion: "Kuyankhulana kwanu ndi chiyani?",
  ReturnPolicyAnswer:
    "Tili ndi malamulo a 30-day adzabwerera pa zinthu zonse. Chonde onani tsamba lathu la malamulo abwereranso kuti mudziwe zambiri.",
  InternationalShippingQuestion: "Kodi mukupereka kutumiza kwadziko lonse?",
  InternationalShippingAnswer:
    "Inde, timatumiza ku mitundu yosiyanasiyana ya dziko. Ndalama za kutumiza zimatha kusiyana kutengera komwe mukupita.",
};
