export const translationKeys = {
    Users: "Atsogoleri",
    StaffStatuses: "Mitemo ya aphale",
    Genders: "Akazi na amuna",
    Roles: "Mabasa",
    Category: "Gulu",
    Product: "Cinthu",
    Modules: "Zigawo",
    Actions: "Mabasa",
    Permissions: "Mphambvu",
    CompanyConfiguration: "Kusankhula kwa kampani",
    SystemConfiguration: "Kusankhula kwa ndondomeko",
    DistributionReport: "Lipoti ya kugawa",
    AccessControl: "Utongi wakupita",
    Products: "Zinthu",
    Settings: "Kusankhula",
    Reports: "Maripoti",
    ProfilePicture: "Chithunzithunzi cha munthu",
    FullName: "Dzina yense",
    Email: "Imelo",
    Password: "Fungulo",
    PhoneNumber: "Nambala ya foni",
    DateOfBirth: "Ntsiku yakubadwa",
    RecruitmentDate: "Ntsiku yakutengwa ntchito",
    UserRole: "Basa ya mutsogoleri",
    Status: "Mamonekedwe",
    Gender: "Mkazi kapena Mwamuna",
    Description: "Kulongosola",
    RoleName: "Dzina ya basa",
    CategoryName: "Dzina ya gulu",
    ProductName: "Dzina ya cinthu",
    Price: "Mutengo",
    Images: "Zithunzithunzi",
    NumberOfReviews: "Kuwerenga maganizo",
    SalesVolume: "Kukula kwa malonda",
    StockStatus: "Mamonekedwe a katundu",
    DiscountPercentage: "Peresenti yakuchepesa",
    TimeAdded: "Nthawi yowonjezera",
    Brand: "Mtundu",
    MaterialsUsed: "Zinthu zogwiritsira ntchito",
    Color: "Mtundu",
    Size: "Kukula",
    Features: "Zinthu zapadera",
    Tags: "Zizindikiro",
    WarrantyPeriod: "Nthawi ya chitsimikizo",
    ManufacturerDetails: "Zodziwika za wopanga",
    ModuleName: "Dzina ya chigawo",
    Action: "Kuchita",
    Create: "Kupanga",
    Read: "Kuwerenga",
    Update: "Kusintha",
    Delete: "Kufafaniza",
    CompanyLogo: "Chizindikiro cha kampani",
    CompanyName: "Dzina ya kampani",
    CompanyGoogleMapLink: "Ulalo wa Google Map wa kampani",
    CompanyEmails: "Maimelo a kampani",
    CompanyPhoneNumbers: "Manambala a foni a kampani",
    CompanySocialMediaLinks: "Maulalo a social media a kampani",
    CompanyAddress: "Adiresi ya kampani",
    Location: "Malo",
    Motto: "Mau otsogolera",
    SystemLogo: "Chizindikiro cha ndondomeko",
    ApplicationName: "Dzina ya pulogalamu",
    ApplicationVersion: "Mtundu wa pulogalamu",
    Language: "Chinenero",
    GoogleConfiguration: "Kusankhula kwa Google",
    ClientId: "ID ya kasitomala",
    ClientSecret: "Chinsinsi cha kasitomala",
    UserEmail: "Imelo ya mutsogoleri",
    UserPassword: "Fungulo ya mutsogoleri",
    AccessToken: "Chizindikiro chakupita",
    RefreshToken: "Chizindikiro chakukonzanso",
    StripeConfiguration: "Kusankhula kwa Stripe",
    PublishableKey: "Fungulo yosindikizika",
    SecretKey: "Fungulo yachinsinsi",
    PaypalConfiguration: "Kusankhula kwa Paypal",
    JwtConfiguration: "Kusankhula kwa JWT",
    DatabaseConfiguration: "Kusankhula kwa database",
    DatabaseUrl: "URL ya database",
    FirebaseConfiguration: "Kusankhula kwa Firebase",
    ApiKey: "Fungulo ya API",
    AuthDomain: "Dera lovomerezeka",
    ProjectId: "ID ya pulojekiti",
    StorageBucket: "Malo osungiramo",
    MessagingSenderId: "ID yotumiza mauthenga",
    AppId: "ID ya pulogalamu",
    TwilioConfiguration: "Kusankhula kwa Twilio",
    AccountSid: "SID ya akaunti",
    AuthToken: "Chizindikiro chovomerezeka",
    TwilioNumber: "Nambala ya Twilio",
    AmazonS3Configuration: "Kusankhula kwa Amazon S3",
    AccessKeyId: "ID ya fungulo yakupita",
    BucketName: "Dzina ya malo osungiramo",
    OpenAiConfiguration: "Kusankhula kwa OpenAI",
    LoginPageLayout: "Maonekedwe a tsamba yakupita",
    ApplicationDescription: "Kulongosola kwa pulogalamu",
    MaintenanceMessage: "Uthenga wakonza",
    MaintenanceMode: "Njira yakonza",
    Name: "Dzina",
    Link: "Ulalo",
    Icon: "Chizindikiro",
  
    Home: "Kunyumba",
    Statistics: "Ziwerengero",
    ExportCSV: "Kutulutsa CSV",
    SelectAll: "Sankha zonse",
    Ascending: "Kukwera",
    Descending: "Kutsika",
    Refresh: "Konzanso",
    Filter: "Sefa",
    Apply: "Gwiritsani ntchito",
    Cancel: "Lekani",
    Reset: "Bwezeretsa",
    BulkDelete: "Fafanizani zambiri",
    BulkUpdate: "Sinthani zambiri",
    DownloadCSV: "Tsitsani CSV",
    ConfirmBulkDelete: "Tsimikizani kufafaniza zambiri",
    SelectAction: "Sankhani chochita",
    NoRecordsFound: "Palibe zolemba zopezeka",
    QuickStats: "Ziwerengero zachangu",
    Close: "Tsekani",
    AreYouSure: "Kodi muli otsimikiza?",
    DoYouWantToLogout: "Kodi mukufuna kutuluka?",
    Warning: "Chenjezo",
    YesLogout: "Inde, ndituluke!",
    LoggedOut: "Mwatuluka!",
    ProfileSettings: "Kusankhula kwa mbiri",
    Settings: "Kusankhula",
    Logout: "Tulukani",
    Role: "Basa",
    Previous: "Zapitazo",
    Next: "Zotsatira",
    Records: "Zolemba",
    Apply: "Gwiritsani ntchito",
    Submit: "Tumizani",
    Processing: "Tikukonza...",
    Add: "Onjezani",
    SelectAnOption: "Sankhani chosankha",
    Browse: "Fufuzani",
    AddFiles: "Onjezani mafayilo",
    Upload: "Kwezani",
    Ok: "Chabwino",
    QuickActions: "Zochita mwachangu",
    UpdatePassword: "Sinthani fungulo",
    CurrentPassword: "Fungulo yamakono",
    NewPassword: "Fungulo yatsopano",
    ConfirmNewPassword: "Tsimikizani fungulo yatsopano",
    DeleteWarning: "Simungathe kubwezeretsa izi!",
    YesDelete: "Inde, fafanizani!",
    Deleted: "Zafafanizidwa!",
    DeleteSuccess: "Zolemba zanu zafafanizidwa.",
    Error: "Pali vuto!",
    Success: "Zapambana!",
    DeleteError: "Pali vuto pofafaniza zolemba zanu.",
    BulkUpdateSuccess: "Zolemba zanu zakonzedwa.",
    BulkUpdateError: "Pali vuto pokonza zolemba zanu zambiri.",
    ConfirmBulkDelete: "Tsimikizani kufafaniza zambiri",
    ConfirmBulkDeleteMessage: "Kodi muli otsimikiza kuti mukufuna kufafaniza zolemba izi?",
    Cancelled: "Zalekedzwa",
    StillLoggedIn: "Mudakali mulowa.",
    Profile: "Mbiri",
    NoFileChosen: "Palibe fayilo yosankhidwa",
  };