export const translationKeys = {
  Users: "Ŵagwiriska ntchito",
  StaffStatuses: "Kayimiliro ka ŵantchito",
  Genders: "Viyerezgero",
  Roles: "Maudindo",
  Category: "Gulu",
  Product: "Katundu",
  Modules: "Vigaŵa",
  Actions: "Vyakuchita",
  Permissions: "Maufulu",
  CompanyConfiguration: "Kusankhana kwa kampani",
  SystemConfiguration: "Kusankhana kwa ndondomeko",
  DistributionReport: "Lipoti la kugaŵa",
  AccessControl: "Ulamuliro wakunjira",
  Products: "Katundu",
  Settings: "Vyakusankhana",
  Reports: "Malipoti",
  ProfilePicture: "Chithuzithuzi cha munthu",
  FullName: "Zina lose",
  Email: "Imelo",
  Password: "Lizgu lachisisi",
  PhoneNumber: "Nambala ya foni",
  DateOfBirth: "Zuŵa lakubabika",
  RecruitmentDate: "Zuŵa lakulembeka ntchito",
  UserRole: "Udindo wa muliska ntchito",
  Status: "Kayimiliro",
  Gender: "Chiyerezgero",
  Description: "Kufotokozera",
  RoleName: "Zina la udindo",
  CategoryName: "Zina la gulu",
  ProductName: "Zina la katundu",
  Price: "Mtengo",
  Images: "Vithuzithuzi",
  NumberOfReviews: "Chiwelengero cha maganizo",
  SalesVolume: "Kukula kwa malonda",
  StockStatus: "Kayimiliro ka katundu",
  DiscountPercentage: "Peresenti yakuchepeskeka",
  TimeAdded: "Nyengo yakuŵikika",
  Brand: "Mtundu",
  MaterialsUsed: "Vinthu vyakugwiriskika ntchito",
  Color: "Mtundu",
  Size: "Ukulu",
  Features: "Vyakupatulika",
  Tags: "Vimanyikwiro",
  WarrantyPeriod: "Nyengo ya chisimikizgo",
  ManufacturerDetails: "Vyakukhwaskana na wakupanga",
  ModuleName: "Zina la chigaŵa",
  Action: "Chakuchita",
  Create: "Kupanga",
  Read: "Kuŵazga",
  Update: "Kusintha",
  Delete: "Kufufuta",
  CompanyLogo: "Chimanyikwiro cha kampani",
  CompanyName: "Zina la kampani",
  CompanyGoogleMapLink: "Ulalo wa Google Map wa kampani",
  CompanyEmails: "Maimelo gha kampani",
  CompanyPhoneNumbers: "Manambala gha foni gha kampani",
  CompanySocialMediaLinks: "Malalo gha social media gha kampani",
  CompanyAddress: "Adilesi ya kampani",
  Location: "Malo",
  Motto: "Mazgu ghakurongozga",
  SystemLogo: "Chimanyikwiro cha ndondomeko",
  ApplicationName: "Zina la pulogalamu",
  ApplicationVersion: "Mtundu wa pulogalamu",
  Language: "Chiyowoyero",
  GoogleConfiguration: "Kusankhana kwa Google",
  ClientId: "ID ya kasitomala",
  ClientSecret: "Chisisi cha kasitomala",
  UserEmail: "Imelo ya muliska ntchito",
  UserPassword: "Lizgu lachisisi la muliska ntchito",
  AccessToken: "Chimanyikwiro chakunjira",
  RefreshToken: "Chimanyikwiro chakuwuskira",
  StripeConfiguration: "Kusankhana kwa Stripe",
  PublishableKey: "Makiyi ghakuvumbukwa",
  SecretKey: "Makiyi ghachisisi",
  PaypalConfiguration: "Kusankhana kwa Paypal",
  JwtConfiguration: "Kusankhana kwa JWT",
  DatabaseConfiguration: "Kusankhana kwa database",
  DatabaseUrl: "URL ya database",
  FirebaseConfiguration: "Kusankhana kwa Firebase",
  ApiKey: "Makiyi gha API",
  AuthDomain: "Chigaŵa chakuzomerezgeka",
  ProjectId: "ID ya pulojekiti",
  StorageBucket: "Malo ghakusungira",
  MessagingSenderId: "ID yakutumira mauthenga",
  AppId: "ID ya pulogalamu",
  TwilioConfiguration: "Kusankhana kwa Twilio",
  AccountSid: "SID ya akaunti",
  AuthToken: "Chimanyikwiro chakuzomerezgeka",
  TwilioNumber: "Nambala ya Twilio",
  AmazonS3Configuration: "Kusankhana kwa Amazon S3",
  AccessKeyId: "ID ya makiyi ghakunjira",
  BucketName: "Zina la malo ghakusungira",
  OpenAiConfiguration: "Kusankhana kwa OpenAI",
  LoginPageLayout: "Kayimiliro ka paji yakunjirira",
  ApplicationDescription: "Kufotokozera kwa pulogalamu",
  MaintenanceMessage: "Uthenga wakukonzeskera",
  MaintenanceMode: "Nthowa yakukonzeskera",
  Name: "Zina",
  Link: "Ulalo",
  Icon: "Chimanyikwiro",

  Home: "Kunyumba",
  Statistics: "Viŵerengero",
  ExportCSV: "Kufumiska CSV",
  SelectAll: "Sankhani vyose",
  Ascending: "Kukwera",
  Descending: "Kukhira",
  Refresh: "Wuskani",
  Filter: "Sefani",
  Apply: "Gwiriskani ntchito",
  Cancel: "Lekani",
  Reset: "Werezganiso",
  BulkDelete: "Fufutani vinandi",
  BulkUpdate: "Sinthani vinandi",
  DownloadCSV: "Torani CSV",
  ConfirmBulkDelete: "Khozgani kufufuta vinandi",
  SelectAction: "Sankhani chakuchita",
  NoRecordsFound: "Palije vyakulemba vyakusangika",
  QuickStats: "Viŵerengero vyaluŵiro",
  Close: "Jalani",
  AreYouSure: "Kasi muli ŵakusimikizga?",
  DoYouWantToLogout: "Kasi mukukhumba kufuma?",
  Warning: "Chenjezo",
  YesLogout: "Enya, nifume!",
  LoggedOut: "Mwafuma!",
  ProfileSettings: "Vyakukhwaskana na mbiri",
  Settings: "Vyakusankhana",
  Logout: "Fumani",
  Role: "Udindo",
  Previous: "Vyamale",
  Next: "Vyakwiza",
  Records: "Vyakulemba",
  Apply: "Gwiriskani ntchito",
  Submit: "Tumizgani",
  Processing: "Tikukonzga...",
  Add: "Songezgani",
  SelectAnOption: "Sankhani chakusankha",
  Browse: "Pendani",
  AddFiles: "Songezgani mafayilo",
  Upload: "Kwezgani",
  Ok: "Vyaweme",
  QuickActions: "Vyakuchita mwaluŵiro",
  UpdatePassword: "Sinthani lizgu lachisisi",
  CurrentPassword: "Lizgu lachisisi lamakono",
  NewPassword: "Lizgu lachisisi liphya",
  ConfirmNewPassword: "Khozgani lizgu lachisisi liphya",
  DeleteWarning: "Mungazakuwezgako ivi chara!",
  YesDelete: "Enya, fufutani!",
  Deleted: "Vyafufutika!",
  DeleteSuccess: "Vyakulemba vyinu vyafufutika.",
  Error: "Pali chiheni!",
  Success: "Vyamuchita!",
  DeleteError: "Pali chiheni pakufufuta vyakulemba vyinu.",
  BulkUpdateSuccess: "Vyakulemba vyinu vyasinthika.",
  BulkUpdateError: "Pali chiheni pakusintha vyakulemba vyinu vinandi.",
  ConfirmBulkDelete: "Khozgani kufufuta vinandi",
  ConfirmBulkDeleteMessage:
    "Kasi muli ŵakusimikizga kuti mukukhumba kufufuta vyakulemba ivi?",
  Cancelled: "Vyalekezgeka",
  StillLoggedIn: "Muchali mukunjira.",
  Profile: "Mbiri",
  NoFileChosen: "Palije fayilo yakusoreka",
  WelcomeToPansikaOnline: "Tikutumbika ku Pansika Online",
  OneStopMarketplace: "Msika wako umodzi wopangira zinthu zonse",
  ExploreProductRange:
    "Fufuzani zinthu zathu zambiri zomwe zidakonzedwa kuti zikwaniritse zosowa zanu zonse.",
  MarketplaceProducts: "Zinthu za msika",
  StartShopping: "Yambani kugula",
  ExclusiveOffers: "Zopereka zapadera",
  BestDealsForYou: "Zokulitsa zabwino kwambiri zongokuthandizani",
  DontMissOffers:
    "Musapuse zomwe tili nazo zapadera komanso zotsika mtengo zomwe zili zochepa.",
  ViewOffers: "Onani zopereka",
  NewArrivals: "Zatsopano",
  DiscoverWhatsNew: "Fufuzani zomwe zatsopano",
  CheckLatestArrivals:
    "Onani zomwe zatsopano mu zigawo zosiyanasiyana zomwe zidakonzedwa kwa inu.",
  SeeNewProducts: "Onani Zatsopano",

  // Magulu
  TopCategories: "Magulu Apamwamba",
  ShopByCategory: "Gulani pogwiritsa ntchito gulu",
  Electronics: "Zida zamagetsi",
  LatestGadgets: "Zida zatsopano ndi zida",
  Fashion: "Chimwene",
  TrendyClothing: "Zovala ndi zinthu zatsopano",
  HomeLiving: "Nyumba & Moyo",
  HomeEssentials: "Zofunikira za nyumba yokongola",
  KitchenDining: "Kicheni & Kusankha",
  QualityKitchenware:
    "Zida zapamwamba za kicheni kwa aliyense wochita ziphuphu",

  // Zinthu zapamwamba
  FeaturedProducts: "Zinthu Zapamwamba",
  SmartphoneXYZ: "Smartphone XYZ",
  WirelessEarbuds: "Ma earbud osavuta",
  FitnessTracker: "Zida za kuyang'anira thanzi",
  GamingLaptop: "Laptop yama games",

  // Zambiri
  WhyChoosePansikaOnline: "N'chifukwa chiyani kusankha Pansika Online?",
  FastShipping: "Kutumiza mwachangu",
  FastShippingDesc:
    "Perekani ma oda anu mwachangu komanso mwachangu, mwachindunji ku tsamba lanu.",
  SecurePayments: "Malipiro otetezeka",
  SecurePaymentsDesc:
    "Gulani ndi chikhulupiliro pogwiritsa ntchito njira zathu zotetezedwa komanso chitetezo cha data.",
  QualityAssurance: "Chitsimikizo cha Khalidwe",
  QualityAssuranceDesc:
    "Timatsimikizira kuti zinthu zonse zikugwirizana ndi mfundo zatsopano zapamwamba musanatumize.",

  // Zotsatira
  TestimonialQuote:
    "Kugula ku Pansika Online kwakhala chithandizo chabwino! Kusiyana komanso khalidwe la zinthu ndi zosangalatsa.",
  TestimonialAuthor: "John Doe",
  TestimonialPosition: "Makasitomala wochita bwino",

  // Kuitana kwa Action
  JoinOurCommunity: "Lowani mu bungwe lathu",
  SubscribeDescription:
    "Dziwani za zinthu zatsopano, zotsatsa zapadera, ndi zambiri.",
  SubscribeNow: "Lembani Tsopano",
  AboutUs: "Zokhudza ife",
  Categories: "Magulu",
  // Zokhudza ife
  AboutPansikaOnline: "Zokhudza Pansika Online",
  CommittedToYourExperience: "Tikhala okonzeka kwa Moyo Wanu",
  PansikaOnlineTeam: "Gulu la Pansika Online",
  OurVision: "Cholinga Chathu",
  OurCoreValues: "Zofunikira Zathu",
  CustomerSatisfaction: "Kuchita bwino kwa Makasitomala",
  CustomerSatisfactionDesc:
    "Tikulimbikira kufuna zofunikira za makasitomala athu.",
  Sustainability: "Kukhala kwanthawi yaitali",
  SustainabilityDesc:
    "Tikugwira ntchito za njira zolemekezeka m'ntchito zathu.",
  CommunityEngagement: "Kukhala pamodzi ndi anthu",
  CommunityEngagementDesc:
    "Timakhala ndi mwayi wokuthandizani ndi kubwerera ku anthu omwe tikhala nawo.",

  // Mafunso Ofunika
  FrequentlyAskedQuestions: "Mafunso Ofunika",
  PaymentMethodsQuestion: "Kodi mukulandira njira ziti zolipira?",
  PaymentMethodsAnswer:
    "Tikulandira makhadi onse apamwamba, PayPal, ndi kutumiza kwa banki.",
  TrackOrderQuestion: "Ndingatani kutsatira maoda anga?",
  TrackOrderAnswer:
    "Mungathe kutsatira kuchita kwa maoda anu mu 'Maoda Anga' gawo la akaunti yanu.",
  ReturnPolicyQuestion: "Kuyankhulana kwanu ndi chiyani?",
  ReturnPolicyAnswer:
    "Tili ndi malamulo a 30-day adzabwerera pa zinthu zonse. Chonde onani tsamba lathu la malamulo abwereranso kuti mudziwe zambiri.",
  InternationalShippingQuestion: "Kodi mukupereka kutumiza kwadziko lonse?",
  InternationalShippingAnswer:
    "Inde, timatumiza ku mitundu yosiyanasiyana ya dziko. Ndalama za kutumiza zimatha kusiyana kutengera komwe mukupita.",
};
