export const translationKeys = {
  Users: "Watumiwa",
  StaffStatuses: "Mawonekanilo ga achibambo",
  Genders: "Uchimbose",
  Roles: "Maundando",
  Category: "Likuga",
  Product: "Chinthu",
  Modules: "Vigawo",
  Actions: "Yakutenda",
  Permissions: "Ulamusi",
  CompanyConfiguration: "Kulonjela kwa kampani",
  SystemConfiguration: "Kulonjela kwa ndondomeko",
  DistributionReport: "Lipoti lya kugawa",
  AccessControl: "Ulamusi wakujigala",
  Products: "Vinthu",
  Settings: "Yakusosya",
  Reports: "Maripoti",
  ProfilePicture: "Chithuzithuzi cha mundu",
  FullName: "Lina lyosope",
  Email: "Imelo",
  Password: "Lisilu",
  PhoneNumber: "Nambala ja simu",
  DateOfBirth: "Lisiku lya kupelagwa",
  RecruitmentDate: "Lisiku lyakusaulila masengo",
  UserRole: "Undando wa mtumiwa",
  Status: "Mawonekanilo",
  Gender: "Uchimbose",
  Description: "Malopelo",
  RoleName: "Lina lya undando",
  CategoryName: "Lina lya likuga",
  ProductName: "Lina lya chinthu",
  Price: "Bei",
  Images: "Ithuzithuzi",
  NumberOfReviews: "Mpingo wa maganisyo",
  SalesVolume: "Ukulu wa masausyo",
  StockStatus: "Mawonekanilo ga vinthu",
  DiscountPercentage: "Asendi yakuchepeska",
  TimeAdded: "Ndawi jakunjasya",
  Brand: "Mtundu",
  MaterialsUsed: "Vinthu vyakutumiwa",
  Color: "Mtundu",
  Size: "Ukulu",
  Features: "Yinoyo",
  Tags: "Yilandilo",
  WarrantyPeriod: "Ndawi ja unansi",
  ManufacturerDetails: "Yelewelesya ya mpanganawo",
  ModuleName: "Lina lya chigawo",
  Action: "Chitendo",
  Create: "Kupanga",
  Read: "Kuwelenga",
  Update: "Kusinda",
  Delete: "Kufuta",
  CompanyLogo: "Chilandilo cha kampani",
  CompanyName: "Lina lya kampani",
  CompanyGoogleMapLink: "Ulalo wa Google Map wa kampani",
  CompanyEmails: "Maimelo ga kampani",
  CompanyPhoneNumbers: "Manambala ga simu ga kampani",
  CompanySocialMediaLinks: "Malalo ga social media ga kampani",
  CompanyAddress: "Adilesi ja kampani",
  Location: "Malo",
  Motto: "Mau gakulongosya",
  SystemLogo: "Chilandilo cha ndondomeko",
  ApplicationName: "Lina lya pulogalamu",
  ApplicationVersion: "Mtundu wa pulogalamu",
  Language: "Chilongwe",
  GoogleConfiguration: "Kulonjela kwa Google",
  ClientId: "ID ja kasitomala",
  ClientSecret: "Chinsisi cha kasitomala",
  UserEmail: "Imelo ja mtumiwa",
  UserPassword: "Lisilu lya mtumiwa",
  AccessToken: "Chilandilo chakujigala",
  RefreshToken: "Chilandilo chakuwichisya",
  StripeConfiguration: "Kulonjela kwa Stripe",
  PublishableKey: "Makiyi gakuwoneka",
  SecretKey: "Makiyi gachinsisi",
  PaypalConfiguration: "Kulonjela kwa Paypal",
  JwtConfiguration: "Kulonjela kwa JWT",
  DatabaseConfiguration: "Kulonjela kwa database",
  DatabaseUrl: "URL ja database",
  FirebaseConfiguration: "Kulonjela kwa Firebase",
  ApiKey: "Makiyi ga API",
  AuthDomain: "Malo gakujitichisya",
  ProjectId: "ID ja pulojekiti",
  StorageBucket: "Malo gakuika",
  MessagingSenderId: "ID jakutumisya mauthenga",
  AppId: "ID ja pulogalamu",
  TwilioConfiguration: "Kulonjela kwa Twilio",
  AccountSid: "SID ja akaunti",
  AuthToken: "Chilandilo chakujitichisya",
  TwilioNumber: "Nambala ja Twilio",
  AmazonS3Configuration: "Kulonjela kwa Amazon S3",
  AccessKeyId: "ID ja makiyi gakujigala",
  BucketName: "Lina lya malo gakuika",
  OpenAiConfiguration: "Kulonjela kwa OpenAI",
  LoginPageLayout: "Mawonekanilo ga peji jakujigala",
  ApplicationDescription: "Malopelo ga pulogalamu",
  MaintenanceMessage: "Uthenga wakuwichisya",
  MaintenanceMode: "Nthowa jakuwichisya",
  Name: "Lina",
  Link: "Ulalo",
  Icon: "Chilandilo",

  Home: "Kunyumba",
  Statistics: "Yakuwalanga",
  ExportCSV: "Kutulupusya CSV",
  SelectAll: "Saula yosope",
  Ascending: "Kukwela",
  Descending: "Kusuluka",
  Refresh: "Wichisya",
  Filter: "Sefa",
  Apply: "Tumiya",
  Cancel: "Leka",
  Reset: "Wichisyano",
  BulkDelete: "Futa yejinji",
  BulkUpdate: "Sinda yejinji",
  DownloadCSV: "Ulusya CSV",
  ConfirmBulkDelete: "Tichisya kufuta yejinji",
  SelectAction: "Saula chitendo",
  NoRecordsFound: "Pangali yakulembedwa yakusimana",
  QuickStats: "Yakuwalanga yakanyamula",
  Close: "Jala",
  AreYouSure: "Uli wakusakikisya?",
  DoYouWantToLogout: "Ukusaka kutuluka?",
  Warning: "Kulanga",
  YesLogout: "Eya, ndituluche!",
  LoggedOut: "Watuluka!",
  ProfileSettings: "Yakusosya ya mbili",
  Settings: "Yakusosya",
  Logout: "Tuluka",
  Role: "Undando",
  Previous: "Yakupita",
  Next: "Yakwisa",
  Records: "Yakulembedwa",
  Apply: "Tumiya",
  Submit: "Tumisya",
  Processing: "Tikupanga...",
  Add: "Njasya",
  SelectAnOption: "Saula chimo",
  Browse: "Lolalola",
  AddFiles: "Njasya mafayilo",
  Upload: "Kwesa",
  Ok: "Yaweme",
  QuickActions: "Yitendo yakanyamula",
  UpdatePassword: "Sinda lisilu",
  CurrentPassword: "Lisilu lya sambano",
  NewPassword: "Lisilu lyambone",
  ConfirmNewPassword: "Tichisya lisilu lyambone",
  DeleteWarning: "Ngawesa kuwiya aya!",
  YesDelete: "Eya, futa!",
  Deleted: "Yafutika!",
  DeleteSuccess: "Yakulembedwa yenu yafutika.",
  Error: "Kwakwanile nganisyo!",
  Success: "Yikatendeka!",
  DeleteError: "Kwakwanile nganisyo pakufuta yakulembedwa yenu.",
  BulkUpdateSuccess: "Yakulembedwa yenu yasindika.",
  BulkUpdateError: "Kwakwanile nganisyo pakusinda yakulembedwa yenu yejinji.",
  ConfirmBulkDelete: "Tichisya kufuta yejinji",
  ConfirmBulkDeleteMessage:
    "Uli wakusakikisya kuti ukusaka kufuta yakulembedwa aya?",
  Cancelled: "Yalekeleka",
  StillLoggedIn: "Uchali ukujigala.",
  Profile: "Mbili",
  NoFileChosen: "Pangali fayilo jakusauliwa",

  WelcomeToPansikaOnline: "Takulandirani ku Pansika Online",
  OneStopMarketplace: "Msika wathu umodzi wopanga zonse",
  ExploreProductRange:
    "Fufuzani zosiyanasiyana zomwe zili mu msika, zomwe zidzakwaniritse zofuna zanu zonse.",
  MarketplaceProducts: "Zinthu za msika",
  StartShopping: "Yambani kugula",
  ExclusiveOffers: "Zopereka zapadera",
  BestDealsForYou: "Zokulitsa zabwino kwambiri zochepa.",
  DontMissOffers:
    "Musapuse zopereka zathu zapadera ndi zotsika mtengo zomwe zili zochepa.",
  ViewOffers: "Onani zopereka",
  NewArrivals: "Zatsopano",
  DiscoverWhatsNew: "Fufuzani zomwe zatsopano.",
  CheckLatestArrivals:
    "Onani zomwe zatsopano mu zigawo zosiyanasiyana zomwe zidakonzedwa kwa inu.",
  SeeNewProducts: "Onani Zatsopano",

  // Magulu
  TopCategories: "Magulu Apamwamba",
  ShopByCategory: "Gulani pogwiritsa ntchito gulu",
  Electronics: "Zida zamagetsi",
  LatestGadgets: "Zida zatsopano ndi zida",
  Fashion: "Chimwene",
  TrendyClothing: "Zovala ndi zinthu zatsopano",
  HomeLiving: "Nyumba & Moyo",
  HomeEssentials: "Zofunikira za nyumba yokongola",
  KitchenDining: "Kicheni & Kusankha",
  QualityKitchenware:
    "Zida zapamwamba za kicheni kwa aliyense wochita ziphuphu",

  // Zinthu zapamwamba
  FeaturedProducts: "Zinthu Zapamwamba",
  SmartphoneXYZ: "Smartphone XYZ",
  WirelessEarbuds: "Ma earbud osavuta",
  FitnessTracker: "Zida za kuyang'anira thanzi",
  GamingLaptop: "Laptop yama games",

  // Zambiri
  WhyChoosePansikaOnline: "N'chifukwa chiyani kusankha Pansika Online?",
  FastShipping: "Kutumiza mwachangu",
  FastShippingDesc:
    "Perekani ma oda anu mwachangu komanso mwachangu, mwachindunji ku tsamba lanu.",
  SecurePayments: "Malipiro otetezeka",
  SecurePaymentsDesc:
    "Gulani ndi chikhulupiliro pogwiritsa ntchito njira zathu zotetezedwa komanso chitetezo cha data.",
  QualityAssurance: "Chitsimikizo cha Khalidwe",
  QualityAssuranceDesc:
    "Timatsimikizira kuti zinthu zonse zikugwirizana ndi mfundo zatsopano zapamwamba musanatumize.",

  // Zotsatira
  TestimonialQuote:
    "Kugula ku Pansika Online kwakhala chithandizo chabwino! Kusiyana komanso khalidwe la zinthu ndi zosangalatsa.",
  TestimonialAuthor: "John Doe",
  TestimonialPosition: "Makasitomala wochita bwino",

  // Kuitana kwa Action
  JoinOurCommunity: "Lowani mu bungwe lathu",
  SubscribeDescription:
    "Dziwani za zinthu zatsopano, zotsatsa zapadera, ndi zambiri.",
  SubscribeNow: "Lembani Tsopano",
  AboutUs: "Zokhudza ife",
  Categories: "Magulu",
  // Zokhudza ife
  AboutPansikaOnline: "Zokhudza Pansika Online",
  CommittedToYourExperience: "Tikhala okonzeka kwa Moyo Wanu",
  PansikaOnlineTeam: "Gulu la Pansika Online",
  OurVision: "Cholinga Chathu",
  OurCoreValues: "Zofunikira Zathu",
  CustomerSatisfaction: "Kuchita bwino kwa Makasitomala",
  CustomerSatisfactionDesc:
    "Tikulimbikira kufuna zofunikira za makasitomala athu.",
  Sustainability: "Kukhala kwanthawi yaitali",
  SustainabilityDesc:
    "Tikugwira ntchito za njira zolemekezeka m'ntchito zathu.",
  CommunityEngagement: "Kukhala pamodzi ndi anthu",
  CommunityEngagementDesc:
    "Timakhala ndi mwayi wokuthandizani ndi kubwerera ku anthu omwe tikhala nawo.",

  // Mafunso Ofunika
  FrequentlyAskedQuestions: "Mafunso Ofunika",
  PaymentMethodsQuestion: "Kodi mukulandira njira ziti zolipira?",
  PaymentMethodsAnswer:
    "Tikulandira makhadi onse apamwamba, PayPal, ndi kutumiza kwa banki.",
  TrackOrderQuestion: "Ndingatani kutsatira maoda anga?",
  TrackOrderAnswer:
    "Mungathe kutsatira kuchita kwa maoda anu mu 'Maoda Anga' gawo la akaunti yanu.",
  ReturnPolicyQuestion: "Kuyankhulana kwanu ndi chiyani?",
  ReturnPolicyAnswer:
    "Tili ndi malamulo a 30-day adzabwerera pa zinthu zonse. Chonde onani tsamba lathu la malamulo abwereranso kuti mudziwe zambiri.",
  InternationalShippingQuestion: "Kodi mukupereka kutumiza kwadziko lonse?",
  InternationalShippingAnswer:
    "Inde, timatumiza ku mitundu yosiyanasiyana ya dziko. Ndalama za kutumiza zimatha kusiyana kutengera komwe mukupita.",
};
